import type { SectionEntry } from './types';

const icon = '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16" stroke-width="2" stroke-linecap="round"/></svg>';

export const piekary9Sections: Record<string, SectionEntry> = {
  piekary9Location: {
    id: 'piekary9Location',
    label: 'Piekary lokalizacja',
    groupId: 'contact',
    hint: 'Interaktywna mapa Leaflet z listą punktów POI, markerami i CTA kontaktowym',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 21s7-5.3 7-12a7 7 0 10-14 0c0 6.7 7 12 7 12zM12 11a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9LocationBlock', dataKey: 'piekary9-location' } },
  },
  piekary9Team: {
    id: 'piekary9Team',
    label: 'Piekary zespół',
    groupId: 'about',
    hint: 'Zdjęcie zespołu z panelem czterech członków inwestycji',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M16 20v-1a4 4 0 00-4-4H7a4 4 0 00-4 4v1m5-9a4 4 0 100-8 4 4 0 000 8zm8 9v-1a4 4 0 00-3-3.9M16 3.1a4 4 0 010 7.8" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9TeamBlock', dataKey: 'piekary9-team' } },
  },
  piekary9ImageText: {
    id: 'piekary9ImageText',
    label: 'Piekary detale',
    groupId: 'content',
    hint: 'Trzy naprzemienne bloki zdjęcie i tekst z listą cech oraz CTA',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 5h7v14H4zM13 5h7v14h-7z" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9ImageTextBlock', dataKey: 'piekary9-image-text' } },
  },
  piekary9QuestionsCta: {
    id: 'piekary9QuestionsCta',
    label: 'Piekary pytania i opiekun',
    groupId: 'cta',
    hint: 'Karta pytań z CTA i panelem opiekuna inwestycji',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 19h.01M9.1 9a3 3 0 115.4 1.8c-.9.8-2.5 1.3-2.5 3.2m-6 0a8 8 0 1112 0" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9QuestionsCtaBlock', dataKey: 'piekary9-questions-cta' } },
  },
  piekary9Faq: {
    id: 'piekary9Faq',
    label: 'Piekary FAQ',
    groupId: 'faq',
    hint: 'Pełny akordeon 28 pytań inwestycji z CTA kontaktowym',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 18h.01M9.1 8.5a3 3 0 115.4 1.8c-.9.8-2.5 1.3-2.5 3.2M12 22a10 10 0 100-20 10 10 0 000 20z" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9FaqBlock', dataKey: 'piekary9-faq' } },
  },
  piekary9Gallery: {
    id: 'piekary9Gallery',
    label: 'Piekary galeria',
    groupId: 'portfolio',
    hint: 'Timeline etapów, bento zdjęć, rozwijanie galerii i pełny lightbox',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 5h16v14H4zM7 15l3-3 2 2 2-2 3 3M8 9h.01" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9GalleryBlock', dataKey: 'piekary9-gallery' } },
  },
  piekary9Navigator: {
    id: 'piekary9Navigator',
    label: 'Piekary nawigator lokali',
    groupId: 'services',
    hint: 'Pełny nawigator lokali z mapą budynku, filtrami, tabelą, modalem i drawerem zakupu',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8M8 13h5" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9NavigatorBlock', dataKey: 'piekary9-navigator-settings' } },
  },
  piekary9ContactForm: {
    id: 'piekary9ContactForm',
    label: 'Piekary formularz kontaktowy',
    groupId: 'contact',
    hint: 'Formularz kontaktowy z pełnym stanem wysyłki i panelem kontaktów',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8M8 13h5M8 17h3" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9ContactFormBlock', dataKey: 'piekary9-contact-form' } },
  },
  piekary9IconFeatures: {
    id: 'piekary9IconFeatures',
    label: 'Piekary infrastruktura',
    groupId: 'services',
    hint: 'Trzy karty mocnych stron inwestycji z ikonami i efektem hover',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 2l3 6 6.6 1-4.8 4.7 1.1 6.6L12 17.2 6.1 20.3l1.1-6.6L2.4 9 9 8l3-6z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9IconFeaturesBlock', dataKey: 'piekary9-icon-features' } },
  },
  piekary9About: {
    id: 'piekary9About',
    label: 'Piekary o projekcie',
    groupId: 'about',
    hint: 'Dwukolumnowy blok o projekcie ze statystykami i punktami przewagi',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8M8 13h5" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9AboutBlock', dataKey: 'piekary9-about' } },
  },
  piekary9Advantages: {
    id: 'piekary9Advantages',
    label: 'Piekary atuty',
    groupId: 'services',
    hint: 'Slider kluczowych atutów z zakładkami, pełnym zdjęciem i CTA',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 3l2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3 6.4 20.2l1.1-6.2L3 9.6l6.2-.9L12 3z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9AdvantagesBlock', dataKey: 'piekary9-advantages' } },
  },
  piekary9Hero: {
    id: 'piekary9Hero',
    label: 'Piekary hero',
    groupId: 'hero',
    hint: 'Pełnoekranowy hero inwestycji z trzema slajdami, overlayem, CTA i paskiem statystyk',
    source: 'piekary9',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14M4 6h16a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V8a2 2 0 012-2z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9HeroBlock', dataKey: 'piekary9-hero' } },
  },
  piekary9Navbar: {
    id: 'piekary9Navbar',
    label: 'Piekary navbar',
    groupId: 'navbar',
    hint: 'Transparentny navbar inwestycji z przełączaniem logo, CTA i mobilnym drawerem',
    source: 'piekary9',
    icon,
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9NavbarBlock', dataKey: 'piekary9-navbar' } },
  },
  piekary9ContactDetails: {
    id: 'piekary9ContactDetails',
    label: 'Piekary stopka kontaktowa',
    groupId: 'footer',
    hint: 'Ciemna stopka inwestycji z biurem sprzedaży, spółką, kontaktem i linkami prawnymi',
    source: 'piekary9',
    icon,
    defaultVariant: 'default',
    variants: { default: { component: 'Piekary9ContactDetailsBlock', dataKey: 'piekary9-contact-details' } },
  },
};
