import type { SectionEntry } from './types';

export const servicesSections: Record<string, SectionEntry> = {
  featuresTrainer: {
    id: 'featuresTrainer', label: 'Korzyści, grid', groupId: 'services', hint: 'Siatka czterech kart korzyści', source: 'kasia',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 3l7 4v5c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V7l7-4z" stroke-width="2" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default', variants: { default: { component: 'KasiaBenefitsBlock', dataKey: 'kasia-benefits' } },
  },
  offerTrainer: {
    id: 'offerTrainer', label: 'Oferta, trzy karty', groupId: 'services', hint: 'Trzy karty etapów współpracy', source: 'kasia',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2" stroke-width="2"/><path d="M8 9h8M8 13h8M8 17h4" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default', variants: { default: { component: 'KasiaOfferBlock', dataKey: 'kasia-offer' } },
  },
  features: {
    id: 'features', label: 'Usługi', groupId: 'services', hint: 'Sekcja usług/ofert z kartami ikon',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: {
      default: { component: 'FeaturesBlock', dataKey: 'features' },
      modernHouseBento: { component: 'ModernHouseServicesBentoBlock', dataKey: 'modern-house-services-bento', source: 'modern-house' },
    },
  },
  novaServices: {
    id: 'novaServices', label: 'Oferta usług', groupId: 'services', hint: 'Autorska sekcja usług dla templateu Nova',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2" stroke-width="2"/><path d="M8 9h8M8 13h8M8 17h4" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesHomeBlock', dataKey: 'nova-services' } },
  },
  servicesStudio: {
    id: 'servicesStudio', label: 'Usługi studio (5 kol)', groupId: 'services', hint: 'Grid 5 usług z ikonami i wave barami (biblioteka heinrich)',
    source: 'heinrich',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesStudioGridBlock', dataKey: 'services-studio' } },
  },
  featuresOffer: {
    id: 'featuresOffer', label: 'Karty ofert (cennik)', groupId: 'services', hint: 'Pricing cards z numeracją i badge (biblioteka tom-ros)',
    source: 'tom-ros',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'FeaturesOfferCardsBlock', dataKey: 'features-offer' } },
  },
  specializationsGrid: {
    id: 'specializationsGrid', label: 'Specjalizacje (grid)', groupId: 'services', hint: 'Wyróżniona karta ze zdjęciem + grid specjalizacji z ikonami (biblioteka tymoteusz)',
    source: 'tymoteusz',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'SpecializationsGridBlock', dataKey: 'specializations-grid' } },
  },
  servicesZigzag: {
    id: 'servicesZigzag', label: 'Usługi zygzak', groupId: 'services', hint: 'Usługi w układzie naprzemiennym: zdjęcie + tekst (biblioteka marek-jodlowski)',
    source: 'marek-jodlowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesZigzagBlock', dataKey: 'services-zigzag' } },
  },
  servicesGrid: {
    id: 'servicesGrid', label: 'Usługi grid (asymetryczny)', groupId: 'services', hint: 'Asymetryczny grid 3+2 kart usług z ServiceCard (biblioteka marek-jodlowski)',
    source: 'marek-jodlowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesGridBlock', dataKey: 'services-grid' } },
  },
  servicesCards: {
    id: 'servicesCards', label: 'Usługi karty (4 kol)', groupId: 'services', hint: 'Grid 4 kart usług z ikonami i przyciskiem CTA (biblioteka marek-jodlowski)',
    source: 'marek-jodlowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesCardsBlock', dataKey: 'services-cards' } },
  },
  featuresGrid: {
    id: 'featuresGrid', label: 'Cechy (grid ikon)', groupId: 'services', hint: 'Grid cech z ikonami i dekoracyjnym kątem (biblioteka marek-jodlowski)',
    source: 'marek-jodlowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M5 3a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2H5zm0 2h14v14H5V5zm4 2v10h6V7H9z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'FeaturesGridBlock', dataKey: 'features-grid' } },
  },
  filterableCards: {
    id: 'filterableCards', label: 'Karty z filtrami', groupId: 'services', hint: 'Katalog kart z filtrami kategorii, widokami grid/list i lazy load (biblioteka promix)',
    source: 'promix',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 6h18M6 12h12M10 18h4" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'CardsFilterableBlock', dataKey: 'filterable-cards' } },
  },
  featureGrid: {
    id: 'featureGrid', label: 'Cechy (grid ikon)', groupId: 'services', hint: 'Siatka kart cech z ikonami, tytułem i opisem (biblioteka promix)',
    source: 'promix',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M5 3a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2H5zm0 2h14v14H5V5zm4 2v10h6V7H9z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'FeatureGridBlock', dataKey: 'feature-grid' } },
  },
  servicesMediaCards: {
    id: 'servicesMediaCards', label: 'Usługi (karty z obrazami)', groupId: 'services', hint: 'Grid kart usług z obrazami naprzemiennie i linkiem strzałki (biblioteka lean-creative)',
    source: 'lean-creative',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 6a2 2 0 012-2h14a2 2 0 012 2v12a2 2 0 01-2 2H5a2 2 0 01-2-2V6zm4 3h10M7 13h6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'ServicesMediaCardsBlock', dataKey: 'services-media-cards' } },
  },
  accommodationCards: {
    id: 'accommodationCards', label: 'Pokoje i domki', groupId: 'services', hint: 'Wspólny renderer kart pokoi i domków z układem mobile scroller oraz desktop grid (biblioteka annawie)',
    source: 'annawie',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 10.5L12 3l9 7.5M5 9v11h14V9M9 20v-6h6v6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'AccommodationCardsBlock', dataKey: 'accommodation-cards' } },
  },
  priceTable: {
    id: 'priceTable', label: 'Tabela cen', groupId: 'services', hint: 'Rozsuwana tabela cen z sortowaniem i miniaturkami (wzorzec piekary9)',
    source: 'annawie',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 5h18M3 9h18M3 13h18M3 17h18" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'PriceTableBlock', dataKey: 'price-table' } },
  },
  saunaPricing: {
    id: 'saunaPricing', label: 'Cennik saun i balii', groupId: 'services', hint: 'Orientacyjne ceny wynajmu sauny i balii (biblioteka stalanowski)',
    source: 'stalanowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'SaunaPricingBlock', dataKey: 'sauna-pricing' } },
  },
  materials: {
    id: 'materials', label: 'Materiały (C24, KVH, BSH)', groupId: 'services', hint: 'Sekcja o materiałach konstrukcyjnych z normami (biblioteka stalanowski)',
    source: 'stalanowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" stroke-width="2" stroke-linecap="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'MaterialsWireframeBlock', dataKey: 'materials' } },
  },
  purInsulation: {
    id: 'purInsulation', label: 'Ocieplenia pianą PUR', groupId: 'services', hint: 'Sekcja o ociepleniach pianą PUR (biblioteka stalanowski)',
    source: 'stalanowski',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M6 18h12M8 18v-2.5a4 4 0 018 0V18M10 12V8m4 4V8m-5-3h6M7 5h10" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'PurInsulationWireframeBlock', dataKey: 'pur' } },
  },
  universityFields: {
    id: 'universityFields', label: 'Kierunki (karty-linki)', groupId: 'services', hint: 'Grid kart-linków z ikonami kierunków i linkiem "zobacz wszystkie" (reimplementacja aleksandra-klisik)',
    source: 'klisik',
    icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 3l9 5-9 5-9-5 9-5zm-7 8v5c0 1.5 3 3 7 3s7-1.5 7-3v-5M5 16.5V20c0 1.5 3 2.5 7 2.5s7-1 7-2.5v-3.5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    defaultVariant: 'default',
    variants: { default: { component: 'UniversityFieldsBlock', dataKey: 'university-fields' } },
  },
};
