import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// AboutLawBlock (kopia sekcji "O nas / biografia" z projektu tymoteusz-juszczak,
// version v2: bio + creds sidebar) to detect regressions in rendering without
// running a full build. Pattern: services-studio-contract.test.ts.

interface CredItem {
  label: string;
  value: string;
}

interface AboutLawData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  bio?: string[];
  creds?: CredItem[];
  image?: { src: string; alt: string };
}

const DEFAULT_IMAGE = {
  src: '/assets/placeholders/image-portrait.svg',
  alt: 'Zdjęcie reprezentacyjne kancelarii prawnej',
};

const PL_DATA: AboutLawData = {
  title: 'O kancelarii',
  bio: [
    'Kancelaria prawna świadczy kompleksową obsługę prawną klientom indywidualnym i biznesowym.',
    'Specjalizujemy się w prawie cywilnym, gospodarczym oraz w sprawach transgranicznych.',
    'Każdą sprawę prowadzimy osobiście, od pierwszej konsultacji po prawomocne zakończenie postępowania.',
  ],
  creds: [
    { label: 'Wpis na listę adwokatów', value: 'Okręgowa Izba Adwokacka' },
    { label: 'Specjalizacja', value: 'Prawo cywilne i gospodarcze' },
    { label: 'Języki', value: 'PL, EN, DE' },
    { label: 'Członkostwo', value: 'Samorząd adwokacki' },
  ],
};

const EN_DATA: AboutLawData = {
  lang: 'en',
  title: 'About the law firm',
  bio: ['The law firm provides comprehensive legal services to individual and business clients.'],
  creds: [
    { label: 'Admission to the bar', value: 'District Bar Association' },
    { label: 'Languages', value: 'PL, EN, DE' },
  ],
};

function renderAboutLawHtml(data: AboutLawData): string {
  const {
    sectionId = 'o-nas',
    title = 'O kancelarii',
    bio = [],
    creds = [],
    image = DEFAULT_IMAGE,
  } = data;

  const bioHtml = bio
    .map((paragraph) => `<p class="leading-relaxed ui-type-body text-brand-dark/70">${paragraph}</p>`)
    .join('');

  const credsHtml = creds
    .map((item) => `
      <div class="flex items-center justify-between gap-2">
        <span class="text-[10px] font-semibold uppercase tracking-[0.2em] text-brand-dark/50">${item.label}</span>
        <span class="text-xs font-semibold text-brand-primary">${item.value}</span>
      </div>`)
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative overflow-hidden scroll-mt-28">
    <div class="ui-container">
      <div class="mx-auto max-w-6xl">
        <h1 class="font-heading font-bold ui-type-section-title mb-14 text-center text-brand-dark">${title}</h1>
        <div class="grid gap-12 md:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.85fr)] lg:gap-16">
          <div class="min-w-0">
            <div class="flex max-w-[46rem] flex-col gap-4">
              ${bioHtml}
            </div>
          </div>
          <div class="md:pl-2">
            <div class="ui-glow-card aspect-[3/4] w-full overflow-hidden rounded-2xl">
              <img src="${image.src}" alt="${image.alt}" class="h-full w-full object-cover" loading="lazy" decoding="async" width="336" height="474">
            </div>
            <div class="mt-5 rounded-2xl border border-brand-dark/10 bg-white p-5">
              <div class="flex flex-col gap-3">
                ${credsHtml}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>`;
}

describe('AboutLawBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, tone page i id', () => {
    const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('o-nas');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('tytuł', () => {
    it('renderuje dokładnie jeden h1 z tytułem', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      expect($('h1').length).toBe(1);
      expect($('h1').text()).toContain('O kancelarii');
    });

    it('h1 jest wyśrodkowany (text-center)', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      expect($('h1').hasClass('text-center')).toBe(true);
    });
  });

  describe('grid', () => {
    it('grid ma proporcje 1.35fr / 0.85fr z desktopa', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const grid = $('.grid');
      expect(grid.hasClass('md:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.85fr)]')).toBe(true);
    });

    it('grid jest mobile-first (gap-12 na mobile, lg:gap-16 na desktopie)', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const grid = $('.grid');
      expect(grid.hasClass('gap-12')).toBe(true);
      expect(grid.hasClass('lg:gap-16')).toBe(true);
    });
  });

  describe('biografia', () => {
    it('renderuje tyle akapitów bio, ile dostarczono', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      expect($('.ui-type-body').length).toBe(3);
    });

    it('akapity używają tokena text-brand-dark/70 zamiast klienckiego koloru', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      $('.ui-type-body').each((_, el) => {
        expect($(el).hasClass('text-brand-dark/70')).toBe(true);
      });
    });

    it('bio nie zawiera linków do izb adwokackich klienta (addLinks usunięte)', () => {
      const html = renderAboutLawHtml(PL_DATA);
      expect(html).not.toContain('ora-warszawa');
      expect(html).not.toContain('rak-brb');
      expect(html).not.toContain('bundesgerichtshof');
      expect(html).not.toContain('<a href');
    });
  });

  describe('zdjęcie', () => {
    it('renderuje img z placeholderem biblioteki', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      expect($('img').length).toBe(1);
      expect($('img').attr('src')).toBe('/assets/placeholders/image-portrait.svg');
    });

    it('zdjęcie ma proporcje 3:4 i klasę glow', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const wrap = $('img').parent();
      expect(wrap.hasClass('aspect-[3/4]')).toBe(true);
      expect(wrap.hasClass('ui-glow-card')).toBe(true);
      expect(wrap.hasClass('rounded-2xl')).toBe(true);
    });
  });

  describe('karta creds', () => {
    it('renderuje kartę z borderem i białym tłem', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const card = $('.rounded-2xl.border');
      expect(card.length).toBe(1);
      expect(card.hasClass('bg-white')).toBe(true);
      expect(card.hasClass('border-brand-dark/10')).toBe(true);
    });

    it('renderuje dokładnie N pozycji creds z danych', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const rows = $('.flex.justify-between');
      expect(rows.length).toBe(4);
    });

    it('każda pozycja ma label (muted) i value (brand)', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      $('.flex.justify-between').each((_, el) => {
        const spans = $(el).children('span');
        expect(spans.length).toBe(2);
        expect(spans.first().hasClass('text-brand-dark/50')).toBe(true);
        expect(spans.last().hasClass('text-brand-primary')).toBe(true);
      });
    });

    it('pierwsza pozycja pokazuje wpis na listę adwokatów', () => {
      const $ = cheerio.load(renderAboutLawHtml(PL_DATA));
      const firstRow = $('.flex.justify-between').first();
      expect(firstRow.text()).toContain('Wpis na listę adwokatów');
      expect(firstRow.text()).toContain('Okręgowa Izba Adwokacka');
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski tytuł i creds', () => {
      const $ = cheerio.load(renderAboutLawHtml(EN_DATA));
      expect($('h1').text()).toContain('About the law firm');
      expect($('.flex.justify-between').length).toBe(2);
      expect($('.flex.justify-between').first().text()).toContain('Admission to the bar');
    });

    it('liczba pozycji creds jest elastyczna (propsy nadpisują JSON)', () => {
      const custom = { ...PL_DATA, creds: [{ label: 'Tylko jedna', value: 'Wartość' }] };
      const $ = cheerio.load(renderAboutLawHtml(custom));
      expect($('.flex.justify-between').length).toBe(1);
    });
  });

  it('nie zawiera href="#" ani klienckich tokenów CSS', () => {
    const html = renderAboutLawHtml(PL_DATA);
    expect(html).not.toContain('href="#"');
    expect(html).not.toContain('--color-accent-primary');
    expect(html).not.toContain('--ui-glow');
  });
});
