import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// CompetitionsBlock (wizualna kopia sekcji zawodow z tom-ros), zeby wykryc
// regresje w renderowaniu bez uruchamiania pelnego builda.
// Wzorzec: hero-cinematic-contract.test.ts i marquee-wall-contract.test.ts.

interface CompetitionMedal {
  src?: string;
  alt?: string;
  title?: string;
}

interface CompetitionImage {
  src?: string;
  alt?: string;
  year?: string;
  featured?: boolean;
  group?: 'personal' | 'athletes';
}

interface CompetitionsData {
  sectionId?: string;
  label?: string;
  title?: string;
  description?: string;
  medals?: CompetitionMedal[];
  images?: CompetitionImage[];
  medalFallback?: string;
  photoFallback?: string;
  athletesTitle?: string;
  headingTag?: string;
}

const DEFAULT_MEDALS: CompetitionMedal[] = [
  { src: '/assets/placeholders/image-square.svg', alt: 'Medal pierwszy', title: 'Medal mistrzostw' },
  { src: '/assets/placeholders/image-square.svg', alt: 'Medal drugi', title: 'Złote osiągnięcie' },
  { src: '/assets/placeholders/image-square.svg', alt: 'Medal trzeci', title: 'Podium zawodów' },
];

const DEFAULT_IMAGES: CompetitionImage[] = [
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Występ na scenie', year: '2025', group: 'personal' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Prezentacja sylwetki', year: '2025', group: 'personal' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Poza na scenie', year: '2024', group: 'personal' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Pozowanie na scenie', year: '2024', group: 'personal' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Zdjęcie z zawodów', year: '', group: 'personal' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Zawodnik na scenie', year: '', group: 'athletes' },
  { src: '/assets/placeholders/image-landscape.svg', alt: 'Zawodnik podczas prezentacji', year: '', group: 'athletes' },
];

// Dlaczego: renderujemy statyczny HTML 1:1 z komponentu, bez importowania Astro
// in vitest, because .astro components require the Astro compiler.
function renderCompetitionsHtml(data: CompetitionsData): string {
  const {
    sectionId = 'zawody',
    label = 'Aktywny sportowiec',
    title = 'Zawody',
    description = '',
    medals: rawMedals = [],
    images: rawImages = [],
    medalFallback = 'Medal z zawodów',
    photoFallback = 'Zdjęcie z zawodów',
    athletesTitle = 'Moje zdjęcia i zawodnicy',
    headingTag = 'h2',
  } = data;

  const medals = Array.isArray(rawMedals) ? rawMedals.filter((medal) => medal?.src) : [];
  const images = Array.isArray(rawImages) ? rawImages.filter((image) => image?.src) : [];
  const personalImages = images.filter((image) => image.group !== 'athletes');
  const athleteImages = images.filter((image) => image.group === 'athletes');

  const headerHtml = `
    <div class="space-y-4">
      <p class="leading-relaxed ui-type-accent-label">${label}</p>
      <${headingTag} class="font-heading font-bold ui-type-section-title">${title}</${headingTag}>
      <p class="leading-relaxed ui-type-body max-w-2xl">${description}</p>
    </div>`;

  // Dlaczego: karta medalu - figure z aspektem 3/4, gradient na hover
  // and a red signature bar at the bottom of the card (scale-x from left).
  const medalHtml = (medal: CompetitionMedal, index: number) => `
    <figure class="ui-glow-card group relative overflow-hidden rounded-lg border border-outline-variant bg-surface-container transition-all duration-300 hover:border-brand-primary" data-lightbox data-href="${medal.src}" data-title="${medal.title || medalFallback}">
      <div class="relative aspect-[3/4] overflow-hidden">
        <img src="${medal.src}" alt="${medal.alt || ''}" loading="${index < 2 ? 'eager' : 'lazy'}" class="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-105" />
        <div class="absolute inset-0 flex items-end bg-gradient-to-t from-black/80 via-black/20 to-transparent p-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
          <figcaption class="ui-type-accent-label">${medal.title || medalFallback}</figcaption>
        </div>
      </div>
      <span class="absolute bottom-0 left-0 h-0.5 w-full origin-left scale-x-0 bg-brand-primary transition-transform duration-500 group-hover:scale-x-100" aria-hidden="true"></span>
    </figure>`;

  // Dlaczego: karta masonry - CSS columns z break-inside-avoid, naturalne
  // photo proportions, year badge in the corner and mask with magnifying glass on hover.
  const masonryCardHtml = (image: CompetitionImage, index: number) => `
    <a href="${image.src}" data-lightbox data-href="${image.src}" data-title="${image.alt || photoFallback}" class="ui-glow-card group relative mb-3 block break-inside-avoid overflow-hidden rounded-lg border border-outline-variant bg-surface-container transition-all duration-300 hover:border-brand-primary md:mb-4" aria-label="${image.alt || photoFallback}">
      <img src="${image.src}" alt="${image.alt || ''}" loading="${index < 6 ? 'eager' : 'lazy'}" class="w-full h-auto transition-transform duration-700 ease-out group-hover:scale-105" />
      ${image.year ? `<span class="ui-type-accent-label absolute left-3 top-3 rounded bg-black/70 px-2 py-1 text-[11px] tracking-[0.2em]">${image.year}</span>` : ''}
      <div class="absolute inset-0 flex items-center justify-center bg-black/0 transition-colors duration-300 group-hover:bg-black/40">
        <svg class="h-8 w-8 text-white opacity-0 transition-all duration-300 group-hover:opacity-100" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M21 21l-4.35-4.35M17 10.5a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
      </div>
    </a>`;

  const medalsHtml = medals.length > 0
    ? `<div class="mt-12 grid grid-cols-2 gap-3 md:gap-4 lg:grid-cols-3">
        ${medals.map((medal, index) => medalHtml(medal, index)).join('')}
      </div>`
    : '';

  const personalHtml = personalImages.length > 0
    ? `<div class="mt-8 columns-1 gap-3 sm:columns-2 md:gap-4 lg:columns-3">
        ${personalImages.map((image, index) => masonryCardHtml(image, index)).join('')}
      </div>`
    : '';

  const athletesHtml = athleteImages.length > 0
    ? `<div class="mt-16">
        <h3 class="font-heading font-bold ui-type-section-title">${athletesTitle}</h3>
        <div class="mt-8 columns-1 gap-3 sm:columns-2 md:gap-4 lg:columns-3">
          ${athleteImages.map((image, index) => masonryCardHtml(image, index)).join('')}
        </div>
      </div>`
    : '';

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    <div class="ui-container relative">
      ${headerHtml}
      ${medalsHtml}
      ${personalHtml}
      ${athletesHtml}
    </div>
  </section>`;
}

describe('CompetitionsBlock, kontrakt renderowania', () => {
  const defaultData: CompetitionsData = {
    label: 'Aktywny sportowiec',
    title: 'Zawody',
    description: 'Startuję w zawodach od 2000 roku.',
    medals: DEFAULT_MEDALS,
    images: DEFAULT_IMAGES,
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderCompetitionsHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('zawody');
  });

  it('renderuje .ui-container', () => {
    const $ = cheerio.load(renderCompetitionsHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje label jako .ui-type-accent-label, tytuł w h2 i opis', () => {
    const $ = cheerio.load(renderCompetitionsHtml(defaultData));
    expect($('.ui-type-accent-label').first().text()).toBe('Aktywny sportowiec');
    expect($('h2').text()).toBe('Zawody');
    expect($('p').last().text()).toContain('Startuję w zawodach');
  });

  describe('pasek medali', () => {
    it('renderuje siatkę medali w gridzie 2/3 kolumn', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const grid = $('figure').parent();
      expect(grid.hasClass('grid')).toBe(true);
      expect(grid.hasClass('grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
      expect($('figure').length).toBe(3);
    });

    it('karty medali mają data-lightbox, data-href i data-title', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const medal = $('figure').first();
      expect(medal.attr('data-lightbox')).toBeDefined();
      expect(medal.attr('data-href')).toBe('/assets/placeholders/image-square.svg');
      expect(medal.attr('data-title')).toBe('Medal mistrzostw');
    });

    it('karty medali mają aspect-[3/4], hover:border-brand-primary i czerwony pasek', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const medal = $('figure').first();
      expect(medal.find('div.relative').hasClass('aspect-[3/4]')).toBe(true);
      expect(medal.hasClass('hover:border-brand-primary')).toBe(true);
      const redBar = medal.find('span');
      expect(redBar.hasClass('bg-brand-primary')).toBe(true);
      expect(redBar.hasClass('scale-x-0')).toBe(true);
      expect(redBar.hasClass('group-hover:scale-x-100')).toBe(true);
    });
  });

  describe('galeria personal (masonry)', () => {
    it('renderuje masonry w columns-1 sm:columns-2 lg:columns-3', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      // Dlaczego: pierwszy masonry (galeria personal) to pierwszy kontener
      // columns, a nie pierwszy link - wyszukujemy po klasach, nie po rodzicu.
      const masonry = $('.columns-1').first();
      expect(masonry.hasClass('sm:columns-2')).toBe(true);
      expect(masonry.hasClass('lg:columns-3')).toBe(true);
      expect(masonry.find('a').length).toBe(5);
    });

    it('karty masonry mają break-inside-avoid i data-lightbox', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const card = $('a').first();
      expect(card.hasClass('break-inside-avoid')).toBe(true);
      expect(card.attr('data-lightbox')).toBeDefined();
      expect(card.attr('data-href')).toBe('/assets/placeholders/image-landscape.svg');
      expect(card.attr('data-title')).toBe('Występ na scenie');
    });

    it('badge roku jest widoczny tylko gdy rok podany', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const withYear = $('a').first().find('span');
      expect(withYear.hasClass('bg-black/70')).toBe(true);
      expect(withYear.text()).toBe('2025');
      expect($('a').eq(4).find('span').length).toBe(0);
    });

    it('karty masonry mają ikonę lupy na hover', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      const card = $('a').first();
      expect(card.find('svg').length).toBe(1);
    });
  });

  describe('galeria zawodników (athletes)', () => {
    it('renderuje drugie masonry z nagłówkiem h3', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      expect($('h3').text()).toBe('Moje zdjęcia i zawodnicy');
      expect($('a').length).toBe(7);
    });
  });

  describe('hierarchia nagłówków', () => {
    it('domyślnie używa h2, zero h1', () => {
      const $ = cheerio.load(renderCompetitionsHtml(defaultData));
      expect($('h2').length).toBe(1);
      expect($('h1').length).toBe(0);
    });

    it('używa h1 gdy headingTag = h1 (podstrony)', () => {
      const $ = cheerio.load(renderCompetitionsHtml({ ...defaultData, headingTag: 'h1' }));
      expect($('h1').length).toBe(1);
      expect($('h2').length).toBe(0);
    });
  });

  describe('stany puste', () => {
    it('nie renderuje siatki medali gdy brak medali', () => {
      const $ = cheerio.load(renderCompetitionsHtml({ ...defaultData, medals: [] }));
      expect($('figure').length).toBe(0);
    });

    it('nie renderuje masonry gdy brak zdjęć', () => {
      const $ = cheerio.load(renderCompetitionsHtml({ ...defaultData, images: [] }));
      expect($('a').length).toBe(0);
      expect($('h3').length).toBe(0);
    });
  });
});
