import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// ContactPremiumBlock (kopia sekcji kontaktowej z projektu promix,
// v1: karta mailto + FAQ accordion w gridzie 2 kolumn), zeby wykryc regresje
// in rendering without running the full build. Pattern: about-law-contract.test.ts.

interface FaqItem {
  question: string;
  answer: string;
}

interface ContactPremiumData {
  eyebrow?: string;
  heading?: string;
  description?: string;
  email?: string;
  responseTime?: string;
  faq?: FaqItem[];
}

const PL_DATA: ContactPremiumData = {
  eyebrow: 'Kontakt',
  heading: 'Porozmawiajmy o Twoich potrzebach',
  description: 'Opowiedz nam o swoim projekcie, a my podpowiemy najlepsze rozwiązanie.',
  email: 'kontakt@przyklad.pl',
  responseTime: 'Odpowiadamy w ciągu 24h',
  faq: [
    { question: 'Jak szybko otrzymam odpowiedź?', answer: 'W ciągu 24 godzin w dni robocze.' },
    { question: 'Czy pierwsza konsultacja jest płatna?', answer: 'Nie, jest bezpłatna.' },
    { question: 'Jak wygląda współpraca?', answer: 'Etapami, z raportowaniem postępów.' },
  ],
};

const EN_DATA: ContactPremiumData = {
  eyebrow: 'Contact',
  heading: "Let's talk about your needs",
  description: 'Tell us about your project.',
  email: 'kontakt@przyklad.pl',
  responseTime: 'We reply within 24 hours',
  faq: [
    { question: 'How quickly will I get a response?', answer: 'Within 24 hours on business days.' },
    { question: 'Is the first consultation free?', answer: 'Yes, it is free.' },
  ],
};

function renderContactPremiumHtml(data: ContactPremiumData): string {
  const {
    eyebrow,
    heading = 'Napisz do nas',
    description,
    email,
    responseTime,
    faq = [],
  } = data;

  const mailHref = email ? `mailto:${email}` : '#';

  const faqHtml = faq
    .map((item) => `
        <details class="group rounded-xl border border-brand-dark/10 bg-white shadow-sm">
          <summary class="flex cursor-pointer items-center justify-between gap-4 p-5 text-sm font-medium text-brand-dark transition-colors hover:text-brand-primary">
            <span>${item.question}</span>
            <i class="ph ph-caret-down text-lg transition-transform duration-200 group-open:rotate-180"></i>
          </summary>
          <div class="border-t border-white/40 px-5 pb-5 pt-3">
            <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/60">${item.answer}</p>
          </div>
        </details>`)
    .join('');

  return `<section class="ui-section relative">
    <div class="pointer-events-none absolute inset-0 z-[1] overflow-hidden" aria-hidden="true">
      <div class="pointer-events-none absolute select-none top-1/2 left-0 -translate-x-1/3 -translate-y-1/2" aria-hidden="true"></div>
      <div class="pointer-events-none absolute select-none top-1/2 right-0 translate-x-1/3 -translate-y-1/2" aria-hidden="true"></div>
    </div>
    <div class="ui-container">
      <div class="relative z-10 mx-auto max-w-4xl">
        <div class="mb-12 text-center md:mb-16">
          ${eyebrow ? `<p class="leading-relaxed ui-type-accent-label mb-4 block">${eyebrow}</p>` : ''}
          <h2 class="font-heading font-bold ui-type-heading-section-lg text-balance">${heading}</h2>
          ${description ? `<p class="leading-relaxed ui-type-lead mx-auto mt-5 max-w-xl text-pretty">${description}</p>` : ''}
        </div>
        <div class="grid grid-cols-1 items-start gap-8 lg:grid-cols-2 lg:gap-12">
          ${email ? `
          <div class="relative overflow-hidden rounded-3xl border border-brand-primary/10 bg-white px-8 py-10 shadow-soft">
            <div class="pointer-events-none absolute inset-x-0 top-0 z-[-1] h-32 opacity-40" aria-hidden="true"></div>
            <div class="mx-auto mb-6 flex size-16 items-center justify-center rounded-2xl bg-brand-primary/10 text-brand-primary">
              <i class="ph ph-envelope-simple text-3xl"></i>
            </div>
            <h3 class="font-heading font-bold ui-type-feature-title mb-3 text-center text-brand-dark">${heading}</h3>
            ${responseTime ? `<p class="leading-relaxed ui-type-text-feature-sm mb-6 text-center text-brand-dark/60">${responseTime}</p>` : ''}
            <a class="ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold ui-button-primary h-11 sm:h-12 px-5 sm:px-8 text-sm sm:text-lg focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50 w-full" href="${mailHref}">
              <span>${email}</span>
            </a>
            <div class="mt-6 flex items-center justify-center gap-2 text-xs text-brand-dark/30">
              <i class="ph ph-check-circle"></i>
              <span>Bezpieczny kontakt</span>
            </div>
          </div>` : ''}
          ${faq.length > 0 ? `
          <div class="flex flex-col gap-4">
            <h3 class="font-heading font-bold ui-type-feature-title mb-2 text-center text-brand-dark lg:text-left">Często zadawane pytania</h3>
            ${faqHtml}
          </div>` : ''}
        </div>
      </div>
    </div>
  </section>`;
}

describe('ContactPremiumBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section i klasą relative', () => {
    const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('relative')).toBe(true);
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje dekoracje tła (kontener orbów)', () => {
    const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
    expect($('.pointer-events-none.absolute.inset-0').length).toBe(1);
    expect($('.pointer-events-none.absolute.inset-0').attr('aria-hidden')).toBe('true');
  });

  describe('nagłówek i opis sekcji', () => {
    it('renderuje eyebrow z klasą accent-label', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('.ui-type-accent-label').text()).toContain('Kontakt');
    });

    it('renderuje dokładnie jeden h2 z nagłówkiem (section-heading-lg)', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').hasClass('ui-type-heading-section-lg')).toBe(true);
      expect($('h2').hasClass('text-balance')).toBe(true);
      expect($('h2').text()).toContain('Porozmawiajmy o Twoich potrzebach');
    });

    it('renderuje opis wariantem lead', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('.ui-type-lead').length).toBe(1);
      expect($('.ui-type-lead').hasClass('max-w-xl')).toBe(true);
      expect($('.ui-type-lead').text()).toContain('Opowiedz nam o swoim projekcie');
    });
  });

  describe('karta mailto', () => {
    it('renderuje dokładnie jeden link mailto z adresem email', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      const mailto = $('a[href^="mailto:"]');
      expect(mailto.length).toBe(1);
      expect(mailto.attr('href')).toBe('mailto:kontakt@przyklad.pl');
      expect(mailto.text()).toContain('kontakt@przyklad.pl');
    });

    it('przycisk mailto używa wariantu ui-button-primary i rozmiaru lg', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      const btn = $('a[href^="mailto:"]');
      expect(btn.hasClass('ui-button')).toBe(true);
      expect(btn.hasClass('ui-button-primary')).toBe(true);
      expect(btn.hasClass('w-full')).toBe(true);
    });

    it('pokazuje czas odpowiedzi i ikonę koperty w karcie', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('.ui-type-text-feature-sm.text-center').text()).toContain('Odpowiadamy w ciągu 24h');
      expect($('.ph-envelope-simple').length).toBe(1);
    });

    it('karta używa tokenów brand zamiast klienckich (border-brand-primary/10, bg-white, shadow-soft)', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      const card = $('.rounded-3xl');
      expect(card.hasClass('border-brand-primary/10')).toBe(true);
      expect(card.hasClass('bg-white')).toBe(true);
      expect(card.hasClass('shadow-soft')).toBe(true);
    });

    it('stopka bezpieczeństwa używa ikony check-circle (shield-check nie istnieje w bibliotece)', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('.ph-check-circle').length).toBe(1);
      expect($('body').text()).toContain('Bezpieczny kontakt');
    });
  });

  describe('FAQ accordion', () => {
    it('renderuje co najmniej 3 pozycje details/summary', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      expect($('details').length).toBeGreaterThanOrEqual(3);
      expect($('details summary').length).toBe(3);
    });

    it('każde details ma pytanie w summary i odpowiedź w treści', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      const details = $('details').first();
      expect(details.find('summary span').text()).toContain('Jak szybko otrzymam odpowiedź?');
      expect(details.find('.ui-type-text-feature-sm').text()).toContain('W ciągu 24 godzin');
    });

    it('faq używa tokena border-brand-dark/10 zamiast border-outline/10 klienta', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      $('details').each((_, el) => {
        expect($(el).hasClass('border-brand-dark/10')).toBe(true);
      });
    });

    it('ikona strzałki używa careta z obrotem po otwarciu (group-open:rotate-180)', () => {
      const $ = cheerio.load(renderContactPremiumHtml(PL_DATA));
      const caret = $('.ph-caret-down').first();
      expect(caret.hasClass('group-open:rotate-180')).toBe(true);
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielskie treści', () => {
      const $ = cheerio.load(renderContactPremiumHtml(EN_DATA));
      expect($('h2').text()).toContain("Let's talk about your needs");
      expect($('.ui-type-lead').text()).toContain('Tell us about your project');
      expect($('details').length).toBe(2);
      expect($('details summary span').first().text()).toContain('How quickly will I get a response?');
    });
  });

  describe('czystość biblioteki (zero danych klienta)', () => {
    it('nie zawiera danych klienta promix', () => {
      const html = renderContactPremiumHtml(PL_DATA);
      expect(html).not.toContain('leancreative');
      expect(html).not.toContain('p.kowalczyk');
      expect(html).not.toContain('+48');
    });

    it('nie zawiera klienckich tokenów CSS ani scroll-reveal', () => {
      const html = renderContactPremiumHtml(PL_DATA);
      expect(html).not.toContain('text-on-surface-variant');
      expect(html).not.toContain('border-outline');
      expect(html).not.toContain('class="reveal');
      expect(html).not.toContain('ph-shield-check');
    });

    it('nie zostawia martwego linku href="#" gdy email jest pusty', () => {
      const $ = cheerio.load(renderContactPremiumHtml({ heading: 'Bez maila' }));
      expect($('a').length).toBe(0);
    });
  });
});
