import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// CrossBorderBlock to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.

interface StepItem {
  title: string;
  description: string;
}

interface AreaItem {
  title: string;
  description: string;
}

interface CrossBorderData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  lead?: string;
  steps?: StepItem[];
  areas?: AreaItem[];
}

// Why: Test data reflects the default JSON section (en) to tests
// they covered the real content of the library, not artificial plugs.
const DEFAULT_STEPS: StepItem[] = [
  { title: 'Consultation', description: 'Tell us about your case.' },
  { title: 'Representation', description: 'We handle your case.' },
  { title: 'Resolution', description: 'We bring the case to completion.' },
];

const DEFAULT_AREAS: AreaItem[] = [
  { title: 'Civil Law', description: 'Claims and contracts.' },
  { title: 'Commercial Law', description: 'Business support.' },
  { title: 'Family Law', description: 'Family matters.' },
  { title: 'Real Estate', description: 'Property matters.' },
  { title: 'Inheritance Law', description: 'Probate matters.' },
  { title: 'Criminal Law', description: 'Criminal defense.' },
];

// Dlaczego: ikony Phosphor przypisane krokom i obszarom, jak w komponencie.
const STEP_ICONS = ['handshake', 'briefcase', 'check-circle'];
const AREA_ICONS = ['gavel', 'buildings', 'users-three', 'house', 'hand', 'shield-chevron'];

function renderCrossBorderHtml(data: CrossBorderData): string {
  const {
    sectionId = 'cross-border',
    lang = 'en',
    title = 'Cross-border assistance',
    lead = 'We help clients with cases involving foreign elements.',
    steps = DEFAULT_STEPS,
    areas = DEFAULT_AREAS,
  } = data;

  const isPl = lang === 'pl';
  const eyebrow = isPl ? 'Pomoc transgraniczna' : 'Cross-border assistance';
  const stepHeading = isPl ? 'Jak wygląda pomoc' : 'How it works';
  const sectionTitle = isPl ? 'Zakres spraw' : 'Practice areas';
  const ctaTitle = isPl ? 'Potrzebujesz pomocy?' : 'Need help?';
  const ctaLabel = isPl ? 'Umów konsultację' : 'Book a consultation';
  const ctaHover = isPl ? 'Wyślij wiadomość' : 'Send a message';

  const stepsHtml = steps
    .map(
      (step, i) => `
      <div class="step-card group rounded-2xl border border-brand-dark/10 bg-white p-6">
        <div class="mb-5 flex size-14 items-center justify-center rounded-xl bg-brand-primary text-2xl text-brand-dark">
          <i class="ph ph-${STEP_ICONS[i % STEP_ICONS.length]}"></i>
        </div>
        <h4 class="font-heading font-bold ui-type-feature-title mb-2 text-xl text-brand-dark">${step.title}</h4>
        <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/70">${step.description}</p>
      </div>`
    )
    .join('');

  const areasHtml = areas
    .map(
      (area, i) => `
      <div class="area-card group flex gap-4 rounded-2xl border border-brand-dark/10 p-5">
        <div class="flex size-14 shrink-0 items-center justify-center rounded-xl bg-brand-primary text-2xl text-brand-dark">
          <i class="ph ph-${AREA_ICONS[i % AREA_ICONS.length]}"></i>
        </div>
        <div class="min-w-0">
          <h4 class="font-heading font-bold ui-type-feature-title mb-1 text-lg text-brand-dark">${area.title}</h4>
          <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/70">${area.description}</p>
        </div>
      </div>`
    )
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative overflow-hidden">
    <div class="pointer-events-none absolute top-0 right-0 h-96 w-96 max-w-full" style="background:radial-gradient(ellipse 60% 60% at 100% 0%, color-mix(in oklab, var(--color-brand-primary) 12%, transparent) 0%, transparent 60%)"></div>
    <div class="ui-container">
      <div class="pt-16 md:pt-20">
        <div class="mb-36 text-center">
          <p class="leading-relaxed ui-type-accent-label mb-4 text-brand-dark" data-motion="fade">${eyebrow}</p>
          <h2 class="font-heading font-bold ui-type-section-title mb-5 text-brand-dark" data-motion="fade">${title}</h2>
          <p class="leading-relaxed ui-type-lead mx-auto max-w-2xl text-brand-dark/70" data-motion="fade">${lead}</p>
        </div>
        <div class="mb-36">
          <div class="mx-auto mb-12 w-3/4 border-t border-brand-dark/10"></div>
          <h3 class="font-heading font-bold ui-type-section-title mb-10 text-center text-brand-dark" style="font-weight:500;letter-spacing:0.06em">${stepHeading}</h3>
          <div class="grid gap-6 md:grid-cols-3">
            ${stepsHtml}
          </div>
        </div>
        <div class="mb-20">
          <div class="mx-auto mb-12 w-3/4 border-t border-brand-dark/10"></div>
          <h3 class="font-heading font-bold ui-type-section-title mb-10 text-center text-brand-dark" style="font-weight:500;letter-spacing:0.06em">${sectionTitle}</h3>
          <div class="grid gap-5 sm:grid-cols-2">
            ${areasHtml}
          </div>
        </div>
        <div class="mx-auto mb-14 w-3/4 border-t border-brand-dark/10"></div>
        <div class="cta-card rounded-2xl border border-brand-dark/10 p-10 text-center" style="background:color-mix(in oklab, var(--color-brand-primary) 12%, transparent)">
          <h3 class="font-heading font-bold ui-type-section-title mb-3 text-brand-dark">${ctaTitle}</h3>
          <p class="leading-relaxed ui-type-body mx-auto mb-8 max-w-md text-brand-dark/70">Book a consultation. I am here to help.</p>
          <a href="/#kontakt" class="ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold ui-button-primary h-11 sm:h-12 px-5 sm:px-8 text-sm sm:text-lg">
            <span class="ui-button-text-wrap">
              <span class="ui-button-text-default">${ctaLabel}</span>
              <span class="ui-button-text-hover">${ctaHover}</span>
            </span>
          </a>
        </div>
      </div>
    </div>
  </section>`;
}

describe('CrossBorder, kontrakt renderowania', () => {
  const defaultData: CrossBorderData = {
    lang: 'en',
    title: 'Cross-border assistance',
    lead: 'We help clients with cases involving foreign elements.',
    steps: DEFAULT_STEPS,
    areas: DEFAULT_AREAS,
  };

  it('renderuje <section> z ui-section, ui-bg-page i id', () => {
    const $ = cheerio.load(renderCrossBorderHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('cross-border');
  });

  it('zawiera .ui-container i gradient orb z brand-primary', () => {
    const $ = cheerio.load(renderCrossBorderHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
    const orb = $('[style*="radial-gradient"]');
    expect(orb.length).toBe(1);
    expect(orb.attr('style')).toContain('var(--color-brand-primary)');
  });

  it('nie zawiera klienckich klas reveal (auto-reveal-item, reveal-group, data-reveal-on-load)', () => {
    const html = renderCrossBorderHtml(defaultData);
    expect(html).not.toContain('auto-reveal-item');
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('data-reveal-on-load');
  });

  it('używa data-motion="fade" zamiast klienckiego reveal na nagłówkach', () => {
    const $ = cheerio.load(renderCrossBorderHtml(defaultData));
    expect($('[data-motion="fade"]').length).toBe(3);
    expect($('h2').attr('data-motion')).toBe('fade');
  });

  describe('nagłówek sekcji', () => {
    it('renderuje eyebrow z ui-type-accent-label', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      expect($('.ui-type-accent-label').length).toBe(1);
      expect($('.ui-type-accent-label').text()).toBe('Cross-border assistance');
    });

    it('renderuje h2 z tytułem i kolorem brand-dark', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const h2 = $('h2');
      expect(h2.text()).toBe('Cross-border assistance');
      expect(h2.hasClass('text-brand-dark')).toBe(true);
      expect(h2.hasClass('ui-type-section-title')).toBe(true);
    });

    it('renderuje lead w kolorze brand-dark/70', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const lead = $('.ui-type-lead');
      expect(lead.length).toBe(1);
      expect(lead.hasClass('text-brand-dark/70')).toBe(true);
    });
  });

  describe('kroki', () => {
    it('renderuje dokładnie 3 karty kroków (step-card)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      expect($('.step-card').length).toBe(3);
    });

    it('karty kroków mają tło bg-white, ramkę brand-dark/10 i hover na grupie', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      $('.step-card').each((_, el) => {
        expect($(el).hasClass('bg-white')).toBe(true);
        expect($(el).hasClass('border-brand-dark/10')).toBe(true);
        expect($(el).hasClass('group')).toBe(true);
      });
    });

    it('każdy krok ma ikonę w kwadracie bg-brand-primary (size-14)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      $('.step-card').each((_, el) => {
        const box = $(el).find('.size-14');
        expect(box.length).toBe(1);
        expect(box.hasClass('bg-brand-primary')).toBe(true);
        expect($(box).find('i.ph').length).toBe(1);
      });
    });

    it('kroki używają ikon handshake, briefcase, check-circle', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      expect($('i.ph-handshake').length).toBe(1);
      expect($('i.ph-briefcase').length).toBe(1);
      expect($('i.ph-check-circle').length).toBe(1);
    });

    it('grid kroków jest mobile-first (grid gap-6 md:grid-cols-3)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const grid = $('.md\\:grid-cols-3');
      expect(grid.length).toBe(1);
      expect(grid.hasClass('grid')).toBe(true);
      expect(grid.hasClass('gap-6')).toBe(true);
    });
  });

  describe('obszary', () => {
    it('renderuje dokładnie 6 kart obszarów (area-card)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      expect($('.area-card').length).toBe(6);
    });

    it('obszary używają ikon gavel, buildings, users-three, house, hand, shield-chevron', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      expect($('i.ph-gavel').length).toBe(1);
      expect($('i.ph-buildings').length).toBe(1);
      expect($('i.ph-users-three').length).toBe(1);
      expect($('i.ph-house').length).toBe(1);
      expect($('i.ph-hand').length).toBe(1);
      expect($('i.ph-shield-chevron').length).toBe(1);
    });

    it('grid obszarów jest mobile-first (grid gap-5 sm:grid-cols-2)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const grid = $('.sm\\:grid-cols-2');
      expect(grid.length).toBe(1);
      expect(grid.hasClass('grid')).toBe(true);
      expect(grid.hasClass('gap-5')).toBe(true);
    });

    it('każdy obszar ma tytuł i opis w osobnej kolumnie', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      $('.area-card').each((_, el) => {
        expect($(el).find('h4').length).toBe(1);
        expect($(el).find('p').length).toBe(1);
      });
    });
  });

  describe('karta CTA', () => {
    it('renderuje .cta-card z tłem color-mix brand-primary', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const cta = $('.cta-card');
      expect(cta.length).toBe(1);
      expect(cta.attr('style')).toContain('var(--color-brand-primary)');
    });

    it('CTA ma przycisk ui-button z wariantem ui-button-primary', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const btn = $('.cta-card a.ui-button');
      expect(btn.length).toBe(1);
      expect(btn.hasClass('ui-button-primary')).toBe(true);
      expect(btn.attr('href')).toBe('/#kontakt');
    });

    it('przycisk ma hoverText (dwa spany: domyślny i hover)', () => {
      const $ = cheerio.load(renderCrossBorderHtml(defaultData));
      const btn = $('.cta-card a.ui-button');
      expect(btn.find('.ui-button-text-wrap').length).toBe(1);
      expect(btn.find('.ui-button-text-default').text()).toBe('Book a consultation');
      expect(btn.find('.ui-button-text-hover').text()).toBe('Send a message');
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderCrossBorderHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
