import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// CtaContactFormBlock (kopia sekcji CTA Kontakt z projektu tymoteusz-juszczak,
// "form" variant) to detect regressions in bare-metal rendering
// full build. Pattern: cross-border-contract.test.ts.

interface CtaContactFormData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  description?: string;
  phone?: string;
  email?: string;
}

// Why: the test data reflects the default JSON of the section (pl), because PL is
// the default language of the block, thanks to which the tests cover real content.
const DEFAULT_PHONE = '+48 123 456 789';
const DEFAULT_EMAIL = 'kontakt@twojafirma.pl';

function renderCtaContactFormHtml(data: CtaContactFormData): string {
  const {
    sectionId = 'kontakt',
    lang = 'pl',
    title = 'Potrzebujesz pomocy prawnej?',
    description = 'Umów się na konsultację. Spotkajmy się osobiście lub online.',
    phone = DEFAULT_PHONE,
    email = DEFAULT_EMAIL,
  } = data;

  const isPl = lang === 'pl';
  const phoneLabel = isPl ? 'Telefon' : 'Phone';
  const emailLabel = isPl ? 'E-mail' : 'E-mail';

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative overflow-hidden scroll-mt-28">
    <div class="pointer-events-none absolute bottom-0 left-1/2 h-64 w-[500px] max-w-full -translate-x-1/2" style="background:radial-gradient(ellipse 50% 100% at center bottom, color-mix(in oklab, var(--color-brand-primary) 10%, transparent) 0%, transparent 60%)"></div>
    <div class="ui-container">
      <div class="mx-auto mb-14 w-3/4 border-t border-brand-dark/10"></div>
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="font-heading font-bold ui-type-section-title mb-5 text-brand-dark">${title}</h2>
        <p class="leading-relaxed ui-type-lead mb-10 text-brand-dark/70">${description}</p>
      </div>
      <div class="mx-auto max-w-2xl space-y-8">
        <div class="flex flex-col gap-4 sm:flex-row">
          <a href="tel:${phone}" class="contact-box flex flex-1 items-center gap-4 rounded-2xl border border-brand-dark/10 bg-white p-5 transition-all duration-200">
            <div class="contact-box__icon flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-primary/40 text-brand-dark transition-all duration-200">
              <i class="ph ph-phone"></i>
            </div>
            <div class="min-w-0">
              <div class="text-xs font-medium uppercase tracking-wider text-brand-dark/50">${phoneLabel}</div>
              <div class="text-sm font-semibold text-brand-dark">${phone}</div>
            </div>
          </a>
          <a href="mailto:${email}" class="contact-box flex min-w-0 flex-1 items-center gap-4 rounded-2xl border border-brand-dark/10 bg-white p-5 transition-all duration-200">
            <div class="contact-box__icon flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-primary/40 text-brand-dark transition-all duration-200">
              <i class="ph ph-envelope"></i>
            </div>
            <div class="min-w-0">
              <div class="text-xs font-medium uppercase tracking-wider text-brand-dark/50">${emailLabel}</div>
              <div class="break-all text-sm font-semibold text-brand-dark">${email}</div>
            </div>
          </a>
        </div>
        <div class="rounded-2xl border border-brand-dark/10 bg-white p-6 sm:p-8">
          <div class="space-y-6">
            <form id="cta-contact-form" data-contact-form></form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <style>
    .contact-box:hover {
      border-color: var(--color-brand-primary) !important;
      background: color-mix(in oklab, var(--color-brand-primary) 15%, transparent) !important;
      box-shadow: 0 0 30px color-mix(in oklab, var(--color-brand-primary) 20%, transparent) !important;
    }
    .contact-box:hover .contact-box__icon {
      background: var(--color-brand-primary) !important;
      color: var(--color-brand-dark) !important;
    }
  </style>`;
}

describe('CtaContactForm, kontrakt renderowania', () => {
  const defaultData: CtaContactFormData = {
    title: 'Potrzebujesz pomocy prawnej?',
    description: 'Umów się na konsultację. Spotkajmy się osobiście lub online.',
    phone: DEFAULT_PHONE,
    email: DEFAULT_EMAIL,
  };

  it('renderuje <section> z ui-section, ui-bg-page, id i scroll-mt', () => {
    const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('kontakt');
    expect($('section').hasClass('scroll-mt-28')).toBe(true);
  });

  it('zawiera .ui-container i gradient orb z brand-primary', () => {
    const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
    const orb = $('[style*="radial-gradient"]');
    expect(orb.length).toBe(1);
    expect(orb.attr('style')).toContain('var(--color-brand-primary)');
  });

  it('ma linię oddzielającą border-brand-dark/10 zamiast klienckiej border-white/10', () => {
    const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
    const divider = $('.border-t');
    expect(divider.length).toBe(1);
    expect(divider.hasClass('border-brand-dark/10')).toBe(true);
    const html = renderCtaContactFormHtml(defaultData);
    expect(html).not.toContain('border-white/10');
  });

  it('nie zawiera klienckich klas reveal ani klienckich tokenów kolorów', () => {
    const html = renderCtaContactFormHtml(defaultData);
    expect(html).not.toContain('auto-reveal-item');
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('data-reveal-on-load');
    expect(html).not.toContain('color-text-primary');
    expect(html).not.toContain('color-text-secondary');
    expect(html).not.toContain('color-text-muted');
    expect(html).not.toContain('color-accent-primary');
    expect(html).not.toContain('color-surface-elevated');
    expect(html).not.toContain('color-border-subtle');
  });

  describe('nagłówek sekcji', () => {
    it('renderuje h2 z tytułem i wariantem ui-type-section-title', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const h2 = $('h2');
      expect(h2.length).toBe(1);
      expect(h2.text()).toBe('Potrzebujesz pomocy prawnej?');
      expect(h2.hasClass('ui-type-section-title')).toBe(true);
      expect(h2.hasClass('text-brand-dark')).toBe(true);
    });

    it('renderuje lead w kolorze brand-dark/70', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const lead = $('.ui-type-lead');
      expect(lead.length).toBe(1);
      expect(lead.hasClass('text-brand-dark/70')).toBe(true);
    });
  });

  describe('boxy kontaktowe', () => {
    it('renderuje dokładnie 2 boxy .contact-box (telefon + e-mail)', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      expect($('.contact-box').length).toBe(2);
    });

    it('box telefonu ma href tel: i etykietę Telefon', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const tel = $('a[href^="tel:"]');
      expect(tel.length).toBe(1);
      expect(tel.find('.text-xs').text()).toBe('Telefon');
      expect(tel.find('.text-sm').text()).toBe(DEFAULT_PHONE);
      expect(tel.hasClass('bg-white')).toBe(true);
      expect(tel.hasClass('border-brand-dark/10')).toBe(true);
    });

    it('box e-maila ma href mailto: i etykietę E-mail', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const mail = $('a[href^="mailto:"]');
      expect(mail.length).toBe(1);
      expect(mail.find('.text-xs').text()).toBe('E-mail');
      expect(mail.find('.text-sm').text()).toBe(DEFAULT_EMAIL);
    });

    it('boxy mają ikony w kwadracie bg-brand-primary/40', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const icons = $('.contact-box__icon');
      expect(icons.length).toBe(2);
      icons.each((_, el) => {
        expect($(el).hasClass('bg-brand-primary/40')).toBe(true);
      });
      expect($('i.ph-phone').length).toBe(1);
      expect($('i.ph-envelope').length).toBe(1);
    });

    it('definiuje hover w <style> z brand-primary (podświetlenie boxa)', () => {
      const html = renderCtaContactFormHtml(defaultData);
      expect(html).toContain('.contact-box:hover');
      expect(html).toContain('border-color: var(--color-brand-primary)');
    });
  });

  describe('formularz kontaktowy', () => {
    it('renderuje kartę formularza z białym tłem i ramką brand-dark/10', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const card = $('.rounded-2xl.bg-white.p-6');
      expect(card.length).toBe(1);
      expect(card.hasClass('border-brand-dark/10')).toBe(true);
      expect(card.hasClass('p-6')).toBe(true);
    });

    it('renderuje formularz ContactForm (form z id cta-contact-form)', () => {
      const $ = cheerio.load(renderCtaContactFormHtml(defaultData));
      const form = $('form#cta-contact-form');
      expect(form.length).toBe(1);
      expect(form.attr('data-contact-form')).toBeDefined();
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderCtaContactFormHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
