import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reproduces the HTML structure generated by
// FooterContactBlock to detect regressions in runless rendering
// full build. Pattern: services-studio-contract.test.ts.

interface FooterContactTestData {
  description?: string;
  contact?: {
    email?: string;
    phone?: string;
    hours?: string;
    saturday?: string;
    city?: string;
    region?: string;
    pricing?: string[];
    social?: { facebook?: string; googleMaps?: string };
    quickLinks?: { label: string; href: string }[];
  };
  legal?: { label: string; href: string }[];
  fullName?: string;
}

const DEFAULT_DATA: FooterContactTestData = {
  description: 'Opis firmy testowej.',
  contact: {
    email: 'kontakt@twojafirma.pl',
    phone: '+48 123 456 789',
    hours: 'Pon - Pt: 08:00 - 16:00',
    saturday: 'Soboty: Do ustalenia',
    city: 'Warszawa',
    region: 'mazowieckie',
    pricing: ['Darmowa wycena', 'Profesjonalne doradztwo'],
    social: {
      facebook: 'https://www.facebook.com/firma',
      googleMaps: 'https://maps.google.com/firma',
    },
    quickLinks: [
      { label: 'O nas', href: '/o-nas/' },
      { label: 'Usługi', href: '/uslugi/' },
    ],
  },
  legal: [
    { label: 'Polityka Prywatności', href: '/polityka-prywatnosci/' },
    { label: 'Regulamin', href: '/regulamin/' },
  ],
  fullName: 'Twoja Firma: nasza pasja',
};

// Why: The renderer must map exactly the same class structure
// co FooterContactBlock.astro, inaczej test straci sens kontraktowy.
function renderFooterContactHtml(data: FooterContactTestData): string {
  const {
    description = '',
    contact = {},
    legal = [],
    fullName = '',
  } = data;

  const contactEmail = contact.email ?? '';
  const contactPhone = contact.phone ?? '';
  const contactHours = contact.hours ?? '';
  const contactSaturday = contact.saturday ?? '';
  const contactCity = contact.city ?? '';
  const contactRegion = contact.region ?? '';
  const contactPricing = contact.pricing ?? [];
  const socialFacebook = contact.social?.facebook || '#';
  const socialGoogleMaps = contact.social?.googleMaps || '#';
  const quickLinks = contact.quickLinks ?? [];
  const legalLinks = legal ?? [];

  return `<footer class="border-t-2 border-brand-dark/10 bg-brand-light text-brand-dark rounded-t-[1.75rem]">
    <div class="ui-container py-8 sm:py-10">
      <div class="footer-contact-panel grid gap-8 rounded-[1.75rem] border border-brand-dark/10 bg-white p-8 text-brand-dark shadow-[0_24px_48px_-24px_color-mix(in_oklab,var(--color-brand-dark)_18%,transparent)] sm:grid-cols-2 lg:grid-cols-4 lg:gap-6 lg:p-10">
        <div class="group flex gap-3">
          <span class="flex shrink-0 items-center justify-center">
            <i class="ph ph-phone flex size-14 items-center justify-center rounded-[1rem] bg-brand-dark/10 text-brand-dark shadow-[0_0.5rem_1rem_color-mix(in_oklab,var(--color-brand-dark)_12%,transparent)] transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.08]"></i>
          </span>
          <div class="space-y-1">
            <span class="footer-contact-label inline-block whitespace-nowrap text-sm font-bold uppercase tracking-[0.08em] text-brand-dark">Kontakt</span>
            <a href="mailto:${contactEmail}" class="block text-sm text-brand-dark/70 transition-colors hover:text-brand-primary">${contactEmail}</a>
            <a href="tel:${contactPhone.replace(/\s/g, '')}" class="block text-sm text-brand-dark/70 transition-colors hover:text-brand-primary">${contactPhone}</a>
          </div>
        </div>
        <div class="group flex gap-3">
          <span class="flex shrink-0 items-center justify-center">
            <i class="ph ph-clock flex size-14 items-center justify-center rounded-[1rem] bg-brand-dark/10 text-brand-dark shadow-[0_0.5rem_1rem_color-mix(in_oklab,var(--color-brand-dark)_12%,transparent)] transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.08]"></i>
          </span>
          <div class="space-y-1">
            <span class="footer-contact-label inline-block whitespace-nowrap text-sm font-bold uppercase tracking-[0.08em] text-brand-dark">Godziny pracy</span>
            <p class="leading-relaxed ui-type-body text-sm text-brand-dark/70">${contactHours}</p>
            <p class="leading-relaxed ui-type-body text-sm text-brand-dark/70">${contactSaturday}</p>
          </div>
        </div>
        <div class="group flex gap-3">
          <span class="flex shrink-0 items-center justify-center">
            <i class="ph ph-map-pin flex size-14 items-center justify-center rounded-[1rem] bg-brand-dark/10 text-brand-dark shadow-[0_0.5rem_1rem_color-mix(in_oklab,var(--color-brand-dark)_12%,transparent)] transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.08]"></i>
          </span>
          <div class="space-y-1">
            <span class="footer-contact-label inline-block whitespace-nowrap text-sm font-bold uppercase tracking-[0.08em] text-brand-dark">Lokalizacja</span>
            <p class="leading-relaxed ui-type-body text-sm text-brand-dark/70">${contactCity}</p>
            <p class="leading-relaxed ui-type-body text-sm text-brand-dark/70">${contactRegion}</p>
          </div>
        </div>
        <div class="group flex gap-3">
          <span class="flex shrink-0 items-center justify-center">
            <i class="ph ph-chat-circle flex size-14 items-center justify-center rounded-[1rem] bg-brand-dark/10 text-brand-dark shadow-[0_0.5rem_1rem_color-mix(in_oklab,var(--color-brand-dark)_12%,transparent)] transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.08]"></i>
          </span>
          <div class="space-y-1">
            <span class="footer-contact-label inline-block whitespace-nowrap text-sm font-bold uppercase tracking-[0.08em] text-brand-dark">Wycena</span>
            ${contactPricing.map((item) => `<p class="leading-relaxed ui-type-body text-sm text-brand-dark/70">${item}</p>`).join('')}
          </div>
        </div>
      </div>

      <div class="mt-8 border-t border-brand-dark/10 px-8 pt-8 sm:pt-10 lg:px-10">
        <div class="footer-grid">
          <div class="footer-about-column space-y-4 flex flex-col items-center text-center sm:items-start sm:text-left">
            <p class="leading-relaxed ui-type-body text-brand-dark/60">${description}</p>
            <div class="flex items-center gap-3">
              <a href="${socialFacebook}" target="_blank" rel="noopener" class="flex size-9 items-center justify-center rounded-xl border border-brand-dark/10 text-brand-dark/50 transition-all duration-300 hover:border-brand-primary/30 hover:bg-brand-primary/10 hover:text-brand-primary" aria-label="Facebook">
                <i class="ph ph-facebook-logo"></i>
              </a>
              <a href="${socialGoogleMaps}" target="_blank" rel="noopener" class="flex size-9 items-center justify-center rounded-xl border border-brand-dark/10 text-brand-dark/50 transition-all duration-300 hover:border-[#34A853]/30 hover:bg-[#34A853]/8 hover:text-[#34A853]" aria-label="Google Maps">
                <i class="ph ph-map-pin"></i>
              </a>
            </div>
          </div>

          <nav aria-label="Szybkie linki" class="justify-self-center text-center sm:justify-self-center">
            <span class="mb-3 block text-sm font-semibold uppercase tracking-[0.12em] text-brand-dark/45">Szybkie linki</span>
            <ul class="flex flex-col items-center gap-2">
              ${quickLinks.map((item) => `<li><a href="${item.href}" class="text-sm text-brand-dark/55 transition-colors hover:text-brand-primary">${item.label}</a></li>`).join('')}
            </ul>
          </nav>

          <nav aria-label="Linki prawne" class="justify-self-center text-center sm:justify-self-end sm:text-right">
            <span class="mb-3 block text-sm font-semibold uppercase tracking-[0.12em] text-brand-dark/45">Informacje</span>
            <ul class="flex flex-col items-center gap-2 sm:items-end">
              ${legalLinks.map((item) => `<li><a href="${item.href}" class="text-sm text-brand-dark/55 transition-colors hover:text-brand-primary">${item.label}</a></li>`).join('')}
            </ul>
          </nav>
        </div>
      </div>

      <div class="mt-8 border-t border-brand-dark/10 pt-5 sm:flex sm:items-center sm:justify-between sm:gap-6">
        <p class="leading-relaxed ui-type-disclaimer not-italic text-brand-dark/45">© ${new Date().getFullYear()} ${fullName}. Wszelkie prawa zastrzeżone.</p>
        <p class="leading-relaxed ui-type-disclaimer not-italic text-brand-dark/45">Realizacja <a href="https://webscale.pro" target="_blank" rel="noopener" class="text-brand-primary hover:underline">WebScale</a></p>
      </div>
    </div>
  </footer>`;
}

describe('FooterContactBlock, kontrakt renderowania', () => {
  it('renderuje <footer> z zaokrągleniem, ramką i tłem brand-light', () => {
    const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
    expect($('footer').length).toBe(1);
    expect($('footer').hasClass('rounded-t-[1.75rem]')).toBe(true);
    expect($('footer').hasClass('border-t-2')).toBe(true);
    expect($('footer').hasClass('border-brand-dark/10')).toBe(true);
    expect($('footer').hasClass('bg-brand-light')).toBe(true);
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('panel kontaktowy', () => {
    it('panel ma klasy kart (bg-white, rounded, grid sm:grid-cols-2 lg:grid-cols-4)', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const panel = $('.footer-contact-panel');
      expect(panel.length).toBe(1);
      expect(panel.hasClass('bg-white')).toBe(true);
      expect(panel.hasClass('rounded-[1.75rem]')).toBe(true);
      expect(panel.hasClass('sm:grid-cols-2')).toBe(true);
      expect(panel.hasClass('lg:grid-cols-4')).toBe(true);
    });

    it('renderuje dokładnie 4 grupy kontaktowe', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('.footer-contact-panel div.group.flex.gap-3').length).toBe(4);
    });

    it('renderuje etykiety grup (Kontakt, Godziny pracy, Lokalizacja, Wycena)', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const labels = $('.footer-contact-label').toArray().map((el) => $(el).text());
      expect(labels).toEqual(['Kontakt', 'Godziny pracy', 'Lokalizacja', 'Wycena']);
    });

    it('linki mailto i tel są poprawne (telefon bez spacji)', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('a[href^="mailto:"]').attr('href')).toBe('mailto:kontakt@twojafirma.pl');
      expect($('a[href^="tel:"]').attr('href')).toBe('tel:+48123456789');
    });
  });

  describe('grid stopki', () => {
    it('grid ma klasę .footer-grid', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('.footer-grid').length).toBe(1);
    });

    it('ma 3 obszary: kolumnę opisu (footer-about-column) i 2 nawigacje', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('.footer-about-column').length).toBe(1);
      expect($('.footer-grid nav').length).toBe(2);
    });
  });

  describe('linki social', () => {
    it('renderuje linki Facebook i Google Maps z aria-label', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('a[aria-label="Facebook"]').length).toBe(1);
      expect($('a[aria-label="Google Maps"]').length).toBe(1);
    });

    it('linki social otwierają się w nowej karcie (target _blank, rel noopener)', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      $('a[aria-label="Facebook"], a[aria-label="Google Maps"]').each((_, el) => {
        expect($(el).attr('target')).toBe('_blank');
        expect($(el).attr('rel')).toBe('noopener');
      });
    });

    it('link Facebook używa adresu z danych', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      expect($('a[aria-label="Facebook"]').attr('href')).toBe('https://www.facebook.com/firma');
    });
  });

  describe('linki nawigacyjne i prawne', () => {
    it('renderuje szybkie linki z danych', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const quickTexts = $('nav[aria-label="Szybkie linki"] a').toArray().map((el) => $(el).text());
      expect(quickTexts).toEqual(['O nas', 'Usługi']);
    });

    it('renderuje linki prawne z danych', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const legalTexts = $('nav[aria-label="Linki prawne"] a').toArray().map((el) => $(el).text());
      expect(legalTexts).toEqual(['Polityka Prywatności', 'Regulamin']);
    });
  });

  describe('dolna belka', () => {
    it('copyright zawiera aktualny rok i pełną nazwę firmy', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const footerText = $('footer').text();
      expect(footerText).toContain(`© ${new Date().getFullYear()} Twoja Firma: nasza pasja`);
      expect(footerText).toContain('Wszelkie prawa zastrzeżone.');
    });

    it('link atrybucji prowadzi do https://webscale.pro w nowej karcie', () => {
      const $ = cheerio.load(renderFooterContactHtml(DEFAULT_DATA));
      const attribution = $('a[href="https://webscale.pro"]');
      expect(attribution.length).toBe(1);
      expect(attribution.text()).toBe('WebScale');
      expect(attribution.attr('target')).toBe('_blank');
      expect(attribution.attr('rel')).toBe('noopener');
    });
  });

  it('nie zawiera klienckiej klasy reveal ani placeholderów klienta', () => {
    const html = renderFooterContactHtml(DEFAULT_DATA);
    expect(html).not.toContain('class="reveal"');
    expect(html).not.toContain('luksusowaprzestrzen');
    expect(html).not.toContain('786 202 542');
  });
});
