import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// HeroLawBlock to detect regressions in rendering without running full render
// builda. Wzorzec: services-studio-contract.test.ts.

interface Cta {
  label: string;
  href: string;
  hoverText?: string;
}

interface Background {
  src: string;
  alt: string;
}

interface HeroLawData {
  sectionId?: string;
  title: string;
  titleAccent: string;
  description: string;
  primaryCTA: Cta;
  secondaryCTA: Cta;
  background: Background;
}

// Why: the default test data is Polish content from hero-law.json (PL is
// default block language). The title intentionally contains the word "Polish-".
// test line breaks in h1.
const DEFAULT_DATA: HeroLawData = {
  sectionId: 'hero-law',
  title: 'Kancelaria prawna. Polsko-niemiecka obsługa prawna.',
  titleAccent: 'Profesjonalna obsługa prawna',
  description: 'Kompleksowa obsługa prawna dla firm i osób prywatnych.',
  primaryCTA: {
    label: 'Umów konsultację',
    hoverText: 'Rezerwuj termin',
    href: '/#kontakt',
  },
  secondaryCTA: {
    label: 'Zakres usług',
    hoverText: 'Zobacz specjalizacje',
    href: '/#uslugi',
  },
  background: {
    src: '/assets/placeholders/image-landscape.svg',
    alt: 'Placeholder zdjęcia panoramicznego',
  },
};

// Why: the same title breaking logic as in the component (regex 1:1
// from the original hero law firm) so that the tested HTML faithfully reproduces
// block rendering, including <br> before "Poland-".
function splitPolishTitle(title: string): { first: string; breakAfter: string | null } {
  const match = title.match(/^(.*\.)\s*([Pp]olsko[‑-].*)$/);
  if (!match) return { first: title, breakAfter: null };
  return { first: match[1], breakAfter: match[2] };
}

// Why: a rough copy of the Button.astro classes, because the test checks the contract
// structured (presence of buttons, variants and hoverText), not a complete list
// Tailwind classes from atom. Full class compatibility is verified by the Astro build.
const BUTTON_BASE_CLASS =
  'ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50';

function renderButton(cta: Cta, variant: string): string {
  return `<a href="${cta.href}" class="${BUTTON_BASE_CLASS} ${variant} h-11 sm:h-12 px-5 sm:px-8 text-sm sm:text-lg [&_svg]:size-5 w-fit self-center sm:self-auto">
    <span class="ui-button-text-wrap">
      <span class="ui-button-text-default">${cta.label}</span>
      <span class="ui-button-text-hover">${cta.hoverText ?? ''}</span>
    </span>
  </a>`;
}

function renderHeroLawHtml(data: HeroLawData): string {
  const { sectionId = 'hero-law' } = data;
  const { first, breakAfter } = splitPolishTitle(data.title);
  const titleHtml = breakAfter ? `${first}<br>${breakAfter}` : first;

  return `<section id="${sectionId}" class="ui-section ui-bg-page hero-law relative flex min-h-dvh items-center overflow-hidden py-0">
    <div class="absolute inset-0 z-0">
      <img src="${data.background.src}" alt="${data.background.alt}" class="h-full w-full object-cover" width="1672" height="941" loading="eager" fetchpriority="high" decoding="async">
      <div class="absolute inset-0 hero-overlay" aria-hidden="true"></div>
    </div>
    <div class="ui-container relative z-10 w-full">
      <div class="hero-pad" style="padding-top:clamp(8rem,18vw,11rem);padding-bottom:clamp(5rem,10vw,8rem)">
        <div class="mx-auto max-w-3xl text-center md:mx-0 md:text-left">
          <p class="leading-relaxed ui-type-accent-label mb-5 text-brand-dark md:mb-6">${data.titleAccent}</p>
          <h1 class="font-heading font-bold ui-type-heading-hero hero-title mb-6 text-brand-dark md:mb-8">${titleHtml}</h1>
          <p class="leading-relaxed hero-description mx-auto mb-10 max-w-xl text-brand-dark/70 md:mx-0">${data.description}</p>
          <div class="hero-actions flex flex-col items-stretch justify-center gap-3 sm:flex-row sm:items-center sm:gap-4 md:justify-start">
            ${renderButton(data.primaryCTA, 'ui-button-primary')}
            ${renderButton(data.secondaryCTA, 'ui-button-outline')}
          </div>
        </div>
      </div>
    </div>
  </section>`;
}

describe('HeroLawBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, ui-bg-page i klasami hero', () => {
    const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').hasClass('relative')).toBe(true);
    expect($('section').hasClass('min-h-dvh')).toBe(true);
    expect($('section').hasClass('overflow-hidden')).toBe(true);
    expect($('section').attr('id')).toBe('hero-law');
  });

  it('zawiera .ui-container z treścią nad tłem (z-10)', () => {
    const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(1);
    expect($('.ui-container').hasClass('relative')).toBe(true);
    expect($('.ui-container').hasClass('z-10')).toBe(true);
  });

  describe('tytuł', () => {
    it('renderuje dokładnie jeden h1', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('h1').length).toBe(1);
    });

    it('h1 zawiera pełny tekst tytułu', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('h1').text()).toBe('Kancelaria prawna.Polsko-niemiecka obsługa prawna.');
    });

    it('łamie tytuł przed członem "Polsko-" (br w h1)', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('h1 br').length).toBe(1);
      expect($('h1').text()).toContain('Polsko-niemiecka');
    });

    it('tytuł EN bez członu "Polsko-" nie ma br (jedna linia)', () => {
      const enData: HeroLawData = {
        ...DEFAULT_DATA,
        title: 'Law firm. Polish-German legal services.',
      };
      const $ = cheerio.load(renderHeroLawHtml(enData));
      expect($('h1 br').length).toBe(0);
      expect($('h1').text()).toBe('Law firm. Polish-German legal services.');
    });

    it('h1 ma klase hero-title i text-brand-dark', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const h1 = $('h1');
      expect(h1.hasClass('hero-title')).toBe(true);
      expect(h1.hasClass('text-brand-dark')).toBe(true);
    });
  });

  describe('etykieta akcentowa i opis', () => {
    it('etykieta akcentowa to ui-type-accent-label nad h1', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const label = $('.ui-type-accent-label');
      expect(label.length).toBe(1);
      expect(label.text()).toBe('Profesjonalna obsługa prawna');
    });

    it('opis renderuje się z klasą hero-description i text-brand-dark/70', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const desc = $('.hero-description');
      expect(desc.length).toBe(1);
      expect(desc.hasClass('text-brand-dark/70')).toBe(true);
      expect(desc.text()).toContain('Kompleksowa obsługa prawna');
    });
  });

  describe('przyciski CTA', () => {
    it('renderuje dokładnie 2 przyciski a.ui-button', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('a.ui-button').length).toBe(2);
    });

    it('pierwszy przycisk jest primary, drugi outline', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const buttons = $('a.ui-button');
      expect(buttons.eq(0).hasClass('ui-button-primary')).toBe(true);
      expect(buttons.eq(1).hasClass('ui-button-outline')).toBe(true);
    });

    it('przyciski wskazują na kotwice z danych', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('a.ui-button').eq(0).attr('href')).toBe('/#kontakt');
      expect($('a.ui-button').eq(1).attr('href')).toBe('/#uslugi');
    });

    it('przyciski mają hoverText w .ui-button-text-hover', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const hovers = $('.ui-button-text-hover');
      expect(hovers.length).toBe(2);
      expect(hovers.eq(0).text()).toBe('Rezerwuj termin');
      expect(hovers.eq(1).text()).toBe('Zobacz specjalizacje');
    });

    it('przyciski mają rozmiar lg i kotwiczą się samoczynnie (w-fit)', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      $('a.ui-button').each((_, el) => {
        expect($(el).hasClass('w-fit')).toBe(true);
        expect($(el).hasClass('self-center')).toBe(true);
      });
    });
  });

  describe('tło', () => {
    it('renderuje img tła z placeholderem i opisowym alt', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      const img = $('img');
      expect(img.length).toBe(1);
      expect(img.attr('src')).toBe('/assets/placeholders/image-landscape.svg');
      expect(img.attr('alt')).toBe('Placeholder zdjęcia panoramicznego');
    });

    it('img tła ma loading="eager" i fetchpriority="high" (LCP)', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('img').attr('loading')).toBe('eager');
      expect($('img').attr('fetchpriority')).toBe('high');
    });

    it('zawiera overlay gradient (hero-overlay) z aria-hidden', () => {
      const $ = cheerio.load(renderHeroLawHtml(DEFAULT_DATA));
      expect($('.hero-overlay').length).toBe(1);
      expect($('.hero-overlay').attr('aria-hidden')).toBe('true');
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderHeroLawHtml(DEFAULT_DATA);
    expect(html).not.toContain('href="#"');
  });
});
