import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import data from '@data/sections/lc-navbar.json';

// Why: The contract test reflects the HTML structure generated by
// LcNavbarBlock (kopia glass floating navbar nad hero z projektu lean-creative:
// 2x2 logo, navigation links, CTA with slide animation) to detect regressions
// in rendering without running the full build. Pattern: about-law-contract.test.ts.
// Note: Astro 7 does not export the Vite plugin for testing, and AstroContainer requires it
// full Astro environment, so we build the HTML manually faithfully to the component.

type LcNavData = (typeof data)['pl'];

function renderNavbarHtml(locale: 'pl' | 'en' = 'pl', propsData?: LcNavData): string {
  const t: LcNavData = propsData ?? data[locale] ?? data.pl;

  const linksHtml = t.links
    .map((link) => `<a class="lc-nav-link rounded-[0.25rem] px-3 py-1.5 text-[0.82rem] font-bold text-white/70 transition hover:bg-white/10 hover:text-white" href="${link.href}">${link.label}</a>`)
    .join('');

  return `<header data-site-header data-lc-navbar class="pointer-events-none absolute left-0 top-0 z-50 w-full">
  <div class="pointer-events-auto mx-auto mt-8 flex w-[calc(100%-2rem)] max-w-[1280px] items-center justify-between gap-3">
    <div class="flex h-14 shrink-0 items-center rounded-[0.25rem] border border-white/15 px-5 backdrop-blur-xl" style="background-color: color-mix(in oklab, var(--color-brand-dark) 55%, transparent)">
      <a href="/" class="flex items-center gap-2.5" aria-label="${t.brandName}">
        <span data-lc-logo class="relative grid h-6 w-6 grid-cols-2 gap-0.5" aria-hidden="true">
          <span class="rounded-xs bg-brand-primary"></span>
          <span class="rounded-xs bg-white/80"></span>
          <span class="rounded-xs bg-brand-accent"></span>
          <span class="rounded-xs bg-[var(--color-brand-dark)]"></span>
        </span>
        <span class="text-[0.95rem] font-extrabold tracking-normal text-white uppercase">${t.brandName} <span class="bg-gradient-to-r from-brand-accent to-brand-primary bg-clip-text text-transparent">${t.brandAccent}</span></span>
      </a>
    </div>
    <div class="flex h-14 min-w-0 items-center gap-0.5 overflow-hidden rounded-[0.25rem] border border-white/15 pl-1 pr-1 backdrop-blur-xl lg:pl-2 lg:pr-1" style="background-color: color-mix(in oklab, var(--color-brand-dark) 55%, transparent)">
      <div class="hidden items-center gap-0.5 lg:flex">
        ${linksHtml}
      </div>
      <a href="${t.cta.href}" class="lc-nav-link lc-btn-slide lc-btn-slide-teal hidden items-center rounded-[0.25rem] bg-brand-accent px-4 py-2.5 text-[0.82rem] font-extrabold text-brand-dark hover:text-white sm:inline-flex">
        ${t.cta.label}
      </a>
      <button data-lc-nav-toggle class="lc-nav-link inline-flex shrink-0 items-center justify-center rounded-[0.25rem] text-white/60 transition hover:bg-white/10 hover:text-white lg:hidden" type="button" aria-label="${t.navToggleLabel}" aria-controls="site-nav-drawer" style="width: clamp(2.75rem, 6vw, 2.75rem); height: clamp(2.75rem, 6vw, 2.75rem);">
        <span class="flex w-4 flex-col gap-[3px]" aria-hidden="true">
          <span class="h-[2px] w-full rounded-full bg-current"></span>
          <span class="h-[2px] w-full rounded-full bg-current"></span>
          <span class="h-[2px] w-full rounded-full bg-current"></span>
        </span>
      </button>
    </div>
  </div>
</header>`;
}

describe('LcNavbarBlock, kontrakt renderowania', () => {
  it('renderuje <header> absolute nad hero z z-50 i pointer-events-none', () => {
    const $ = cheerio.load(renderNavbarHtml());
    expect($('header').length).toBe(1);
    expect($('header').hasClass('absolute')).toBe(true);
    expect($('header').hasClass('top-0')).toBe(true);
    expect($('header').hasClass('z-50')).toBe(true);
    expect($('header').hasClass('pointer-events-none')).toBe(true);
  });

  it('nie jest sticky, tylko absolute (navbar nad hero, nie jak standardowy kit)', () => {
    const $ = cheerio.load(renderNavbarHtml());
    expect($('header').hasClass('sticky')).toBe(false);
    expect($('header').hasClass('fixed')).toBe(false);
  });

  describe('logo 2x2', () => {
    it('renderuje dokładnie 4 kwadraty w grid 2 kolumn', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const logo = $('[data-lc-logo]');
      expect(logo.length).toBe(1);
      expect(logo.hasClass('grid-cols-2')).toBe(true);
      expect(logo.children('span').length).toBe(4);
    });

    it('kwadraty używają tokenów brand (primary, accent, dark) zamiast klienckich', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const squares = $('[data-lc-logo] > span');
      expect(squares.eq(0).hasClass('bg-brand-primary')).toBe(true);
      expect(squares.eq(1).hasClass('bg-white/80')).toBe(true);
      expect(squares.eq(2).hasClass('bg-brand-accent')).toBe(true);
      expect(squares.eq(3).attr('class')).toContain('var(--color-brand-dark)');
    });
  });

  describe('napis brandu', () => {
    it('zawiera brandName z JSON', () => {
      const $ = cheerio.load(renderNavbarHtml());
      expect($('header').text()).toContain('Studio');
    });

    it('człon accent ma gradient brand zamiast klienckiego napisu', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const accent = $('header .bg-gradient-to-r');
      expect(accent.length).toBe(1);
      expect(accent.hasClass('from-brand-accent')).toBe(true);
      expect(accent.hasClass('to-brand-primary')).toBe(true);
      expect(accent.hasClass('bg-clip-text')).toBe(true);
      expect(accent.text()).toBe('Kreatywne');
    });

    it('link logo ma aria-label z brandName', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const logoLink = $('header a[aria-label]').first();
      expect(logoLink.attr('aria-label')).toBe('Studio');
    });
  });

  describe('nawigacja', () => {
    it('renderuje dokładnie 5 linków nawigacji', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const navLinks = $('a.lc-nav-link').filter((_, el) => !$(el).hasClass('lc-btn-slide'));
      expect(navLinks.length).toBe(5);
    });

    it('linki mają kotwice sekcji (formatInternalLink zachowuje kotwice bez zmian)', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const hrefs = $('a.lc-nav-link').filter((_, el) => !$(el).hasClass('lc-btn-slide')).map((_, el) => $(el).attr('href')).get();
      expect(hrefs).toContain('/');
      expect(hrefs).toContain('/#oferta');
      expect(hrefs).toContain('/#o-nas');
      expect(hrefs.every((href) => !href.includes('//#') && !href.endsWith('//'))).toBe(true);
    });

    it('linki używają klasy lc-nav-link z fixem min-height/min-width', () => {
      const $ = cheerio.load(renderNavbarHtml());
      $('a.lc-nav-link').each((_, el) => {
        expect($(el).hasClass('lc-nav-link')).toBe(true);
      });
    });
  });

  describe('CTA', () => {
    it('renderuje CTA jako link z href kotwicy', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const cta = $('a.lc-btn-slide');
      expect(cta.length).toBe(1);
      expect(cta.attr('href')).toBe('/#kontakt');
    });

    it('CTA ma klasę slide z tła brand-dark (lc-btn-slide-teal)', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const cta = $('a.lc-btn-slide');
      expect(cta.hasClass('lc-btn-slide-teal')).toBe(true);
      expect(cta.hasClass('bg-brand-accent')).toBe(true);
      expect(cta.text().trim()).toBe('Umów rozmowę');
    });

    it('CTA jest ukryte na mobile (sm:inline-flex)', () => {
      const $ = cheerio.load(renderNavbarHtml());
      expect($('a.lc-btn-slide').hasClass('sm:inline-flex')).toBe(true);
    });
  });

  describe('mobile toggle', () => {
    it('renderuje button z aria-label i aria-controls', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const toggle = $('button[data-lc-nav-toggle]');
      expect(toggle.length).toBe(1);
      expect(toggle.attr('aria-label')).toBe('Otwórz menu');
      expect(toggle.attr('aria-controls')).toBe('site-nav-drawer');
    });

    it('toggle ma hamburger z 3 kreskami i jest widoczny tylko na mobile', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const toggle = $('button[data-lc-nav-toggle]');
      expect(toggle.hasClass('lg:hidden')).toBe(true);
      expect(toggle.find('span[aria-hidden="true"] > span').length).toBe(3);
    });
  });

  describe('glass tlo (tokeny zamienne)', () => {
    it('kontenery glass używają inline style z tokena brand-dark (mapa zamian)', () => {
      const $ = cheerio.load(renderNavbarHtml());
      const glassContainers = $('header [style*="color-mix"]');
      expect(glassContainers.length).toBe(2);
      glassContainers.each((_, el) => {
        expect($(el).attr('style')).toContain('var(--color-brand-dark)');
      });
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielskie labelki i CTA', () => {
      const $ = cheerio.load(renderNavbarHtml('en'));
      expect($('a.lc-btn-slide').text().trim()).toBe('Book a call');
      expect($('button[data-lc-nav-toggle]').attr('aria-label')).toBe('Open menu');
      expect($('header .bg-gradient-to-r').text()).toBe('Creative');
    });

    it('EN nie miesza polskich treści', () => {
      const $ = cheerio.load(renderNavbarHtml('en'));
      expect($('header').text()).not.toContain('Umów rozmowę');
      expect($('header').text()).not.toContain('Oferta');
    });

    it('props data nadpisuje JSON', () => {
      const custom: LcNavData = {
        brandName: 'Custom',
        brandAccent: 'Brand',
        navToggleLabel: 'Menu',
        links: [{ label: 'Tylko jeden', href: '/#jeden' }],
        cta: { label: 'Dzialaj', href: '/#kontakt' },
      };
      const $ = cheerio.load(renderNavbarHtml('pl', custom));
      expect($('header').text()).toContain('Custom');
      expect($('a.lc-nav-link').filter((_, el) => !$(el).hasClass('lc-btn-slide')).length).toBe(1);
      expect($('a.lc-btn-slide').text().trim()).toBe('Dzialaj');
    });
  });

  it('nie zawiera danych klienta lean-creative ani klienckich tokenow CSS', () => {
    const html = renderNavbarHtml();
    expect(html).not.toContain('Lean Creative');
    expect(html).not.toContain('rozwiazania');
    expect(html).not.toContain('30-minutow');
    expect(html).not.toContain('--ui-navbar-glass-bg');
    expect(html).not.toContain('--ui-logo-deep');
    expect(html).not.toContain('data-reveal');
  });
});
