import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import { formatInternalLink } from '@utils/url';

// Why: The contract test reflects the HTML structure generated by
// LcSubnavBlock (a copy of the sticky subnav from the lean-creative project) to
// detect regressions in rendering without running a full build. Pattern:
// about-law-contract.test.ts (string HTML + cheerio, bez renderToString,
// bo vitest w tym repo nie ma pluginu astro do transpilacji .astro).

interface LinkItem {
  label: string;
  href: string;
}

interface LcSubnavData {
  locale?: 'pl' | 'en';
  brandName?: string;
  brandAccent?: string;
  links?: LinkItem[];
  ctaLabel?: string;
  ctaHref?: string;
}

const PL_LINKS: LinkItem[] = [
  { label: 'Usługi', href: '/#uslugi' },
  { label: 'Proces', href: '/#proces' },
  { label: 'O nas', href: '/o-nas/' },
  { label: 'Blog', href: '/blog/' },
  { label: 'Kontakt', href: '/kontakt/' },
];

const EN_LINKS: LinkItem[] = [
  { label: 'Services', href: '/#services' },
  { label: 'Process', href: '/#process' },
  { label: 'About', href: '/about/' },
  { label: 'Blog', href: '/blog/' },
  { label: 'Contact', href: '/contact/' },
];

const PL_DATA: LcSubnavData = {
  brandName: 'NOVA',
  brandAccent: 'STUDIO',
  links: PL_LINKS,
  ctaLabel: 'Umów rozmowę',
  ctaHref: '/#kontakt',
};

const EN_DATA: LcSubnavData = {
  locale: 'en',
  brandName: 'NOVA',
  brandAccent: 'STUDIO',
  links: EN_LINKS,
  ctaLabel: 'Book a call',
  ctaHref: '/#contact',
};

// Dlaczego: odtwarza klasy renderowane przez Button.astro (variant primary,
// size sm) so that the test checks what will actually come out of the component.
function renderButtonHtml(href: string, label: string): string {
  const classes = [
    'ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold',
    'ui-button-primary',
    'h-9 px-4 text-xs sm:text-sm [&_svg]:size-3.5',
    'focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50',
    'hidden rounded-sm font-extrabold sm:inline-flex',
  ].join(' ');
  return `<a href="${formatInternalLink(href)}" class="${classes}"><span>${label}</span></a>`;
}

function renderLcSubnavHtml(data: LcSubnavData): string {
  const brandName = data.brandName || 'NOVA';
  const brandAccent = data.brandAccent || 'STUDIO';
  const links = data.links || PL_LINKS;
  const ctaLabel = data.ctaLabel || 'Umów rozmowę';
  const ctaHref = data.ctaHref || '/#kontakt';
  const brandFull = `${brandName} ${brandAccent}`;

  const linksHtml = links
    .map(
      (link) => `
        <a href="${formatInternalLink(link.href)}" class="lc-subnav-link rounded-sm px-3 py-1.5 text-[0.82rem] font-bold text-brand-dark/60 transition hover:bg-brand-primary/10 hover:text-brand-primary">${link.label}</a>`,
    )
    .join('');

  return `<header class="sticky left-0 top-0 z-50 w-full border-b border-brand-dark/10 bg-brand-light">
    <div class="mx-auto flex h-18 w-full max-w-[1360px] items-center justify-between gap-3 px-5 sm:px-[var(--spacing-container-px)]">
      <a href="/" class="flex shrink-0 items-center gap-2.5" aria-label="${brandFull}">
        <span class="relative grid h-6 w-6 grid-cols-2 gap-0.5" aria-hidden="true">
          <span class="rounded-xs bg-brand-primary"></span>
          <span class="rounded-xs bg-brand-dark"></span>
          <span class="rounded-xs bg-brand-accent"></span>
          <span class="rounded-xs" style="background:var(--color-brand-dark)"></span>
        </span>
        <span class="text-sm font-extrabold text-brand-dark">${brandName} <span class="text-brand-primary">${brandAccent}</span></span>
      </a>
      <div class="hidden items-center gap-0.5 lg:flex">${linksHtml}
      </div>
      <div class="flex items-center gap-2">
        ${renderButtonHtml(ctaHref, ctaLabel)}
        <button type="button" class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-sm text-brand-dark/60 transition hover:bg-brand-primary/10 hover:text-brand-primary lg:hidden" aria-label="Otwórz menu" aria-controls="site-nav-drawer">
          <span class="flex w-4 flex-col gap-1" aria-hidden="true">
            <span class="h-[2px] w-full rounded-full bg-current"></span>
            <span class="h-[2px] w-full rounded-full bg-current"></span>
            <span class="h-[2px] w-full rounded-full bg-current"></span>
          </span>
        </button>
      </div>
    </div>
  </header>`;
}

describe('LcSubnavBlock, kontrakt renderowania', () => {
  describe('header', () => {
    it('renderuje dokładnie jeden sticky header z tokenami kitu', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      expect($('header').length).toBe(1);
      expect($('header').hasClass('sticky')).toBe(true);
      expect($('header').hasClass('top-0')).toBe(true);
      expect($('header').hasClass('z-50')).toBe(true);
      expect($('header').hasClass('border-brand-dark/10')).toBe(true);
      expect($('header').hasClass('bg-brand-light')).toBe(true);
    });

    it('wewnętrzny kontener ma max-w 1360px, wysokość h-18 i padding z tokena', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const inner = $('header > div');
      expect(inner.hasClass('max-w-[1360px]')).toBe(true);
      expect(inner.hasClass('h-18')).toBe(true);
      expect(inner.hasClass('sm:px-[var(--spacing-container-px)]')).toBe(true);
    });
  });

  describe('logo 2x2', () => {
    it('renderuje grid 2 kolumn z 4 kwadratami', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const logoGrid = $('[aria-hidden="true"].grid');
      expect(logoGrid.length).toBe(1);
      expect(logoGrid.hasClass('grid-cols-2')).toBe(true);
      expect(logoGrid.children('span').length).toBe(4);
    });

    it('kwadraty używają tokenów brand: primary, dark, accent i dark dla --ui-logo-deep', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const squares = $('[aria-hidden="true"].grid > span');
      expect(squares.eq(0).hasClass('bg-brand-primary')).toBe(true);
      expect(squares.eq(1).hasClass('bg-brand-dark')).toBe(true);
      expect(squares.eq(2).hasClass('bg-brand-accent')).toBe(true);
      expect(squares.eq(3).attr('style')).toContain('--color-brand-dark');
    });

    it('logo ma aria-label złożony z brandName i brandAccent', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      expect($('a[aria-label]').attr('aria-label')).toBe('NOVA STUDIO');
    });
  });

  describe('brandName', () => {
    it('renderuje brandName i akcentowany brandAccent', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const text = $('header').text();
      expect(text).toContain('NOVA');
      expect(text).toContain('STUDIO');
    });

    it('brandAccent jest podkreślony kolorem brand-primary', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const accent = $('span.text-brand-primary');
      expect(accent.length).toBe(1);
      expect(accent.text()).toBe('STUDIO');
    });
  });

  describe('linki nawigacji', () => {
    it('renderuje 5+ linków .lc-subnav-link z href', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      expect($('.lc-subnav-link').length).toBe(5);
      $('.lc-subnav-link').each((_, el) => {
        expect($(el).attr('href')).toBeTruthy();
      });
    });

    it('linki mają hover z tokenem brand-primary', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const first = $('.lc-subnav-link').first();
      expect(first.hasClass('hover:bg-brand-primary/10')).toBe(true);
      expect(first.hasClass('hover:text-brand-primary')).toBe(true);
    });

    it('linki są ukryte na mobile i widoczne od lg', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      expect($('header .lg\\:flex').length).toBe(1);
    });

    it('href przechodzą przez formatInternalLink (trailing slash)', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const about = $('.lc-subnav-link').filter((_, el) => $(el).text() === 'O nas');
      expect(about.attr('href')).toBe('/o-nas/');
    });
  });

  describe('CTA', () => {
    it('renderuje Button primary sm z href i etykietą', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const cta = $('.ui-button');
      expect(cta.length).toBe(1);
      expect(cta.hasClass('ui-button-primary')).toBe(true);
      expect(cta.hasClass('ui-type-cta-label')).toBe(true);
      expect(cta.attr('href')).toBe('/#kontakt');
      expect(cta.text()).toContain('Umów rozmowę');
    });

    it('CTA jest ukryty na mobile i widoczny od sm', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const cta = $('.ui-button');
      expect(cta.hasClass('hidden')).toBe(true);
      expect(cta.hasClass('sm:inline-flex')).toBe(true);
    });
  });

  describe('mobile toggle', () => {
    it('renderuje przycisk hamburger z 3 kreskami i aria-label', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const toggle = $('button[aria-label="Otwórz menu"]');
      expect(toggle.length).toBe(1);
      expect(toggle.attr('aria-controls')).toBe('site-nav-drawer');
      expect(toggle.find('span > span').length).toBe(3);
    });

    it('toggle jest widoczny tylko na mobile (lg:hidden)', () => {
      const $ = cheerio.load(renderLcSubnavHtml(PL_DATA));
      const toggle = $('button[aria-label="Otwórz menu"]');
      expect(toggle.hasClass('lg:hidden')).toBe(true);
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielskie etykiety linków i CTA', () => {
      const $ = cheerio.load(renderLcSubnavHtml(EN_DATA));
      expect($('.lc-subnav-link').text()).toContain('Services');
      expect($('.lc-subnav-link').text()).toContain('Contact');
      expect($('.ui-button').text()).toContain('Book a call');
    });
  });

  describe('czystość biblioteki', () => {
    it('nie zawiera danych ani ścieżek klienta lean-creative', () => {
      const html = renderLcSubnavHtml(PL_DATA).toLowerCase();
      expect(html).not.toContain('lean');
      expect(html).not.toContain('rozwiazania');
      expect(html).not.toContain('wiedza');
      expect(html).not.toContain('lc-scroll-nav');
    });

    it('nie zawiera klienckich tokenów CSS ani hooków JS', () => {
      const html = renderLcSubnavHtml(PL_DATA);
      expect(html).not.toContain('border-outline');
      expect(html).not.toContain('bg-primary-container');
      expect(html).not.toContain('text-on-surface-variant');
      expect(html).not.toContain('--ui-logo-deep');
      expect(html).not.toContain('data-reveal');
      expect(html).not.toContain('data-lc-logo');
      expect(html).not.toContain('data-lc-nav-toggle');
    });

    it('propsy nadpisują JSON (elastyczność danych)', () => {
      const custom = { ...PL_DATA, ctaLabel: 'Napisz do nas', links: [{ label: 'Jeden link', href: '/kontakt/' }] };
      const $ = cheerio.load(renderLcSubnavHtml(custom));
      expect($('.ui-button').text()).toContain('Napisz do nas');
      expect($('.lc-subnav-link').length).toBe(1);
    });
  });
});
