import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reproduces the HTML structure generated by
// NavbarContactBlock to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.

interface NavbarContactData {
  menu: { label: string; href: string }[];
  cta: { label: string; href: string; hoverText?: string };
  phone: string;
  email: string;
  city: string;
  hours: string;
  facebookUrl?: string;
}

const DEFAULT_DATA: NavbarContactData = {
  menu: [
    { label: 'O nas', href: '/o-nas/' },
    { label: 'Usługi', href: '/uslugi/' },
    { label: 'Cennik', href: '/cennik/' },
    { label: 'Blog', href: '/blog/' },
  ],
  cta: { label: 'Kontakt', href: '/kontakt/', hoverText: 'Pisz!' },
  phone: '+48 123 456 789',
  email: 'kontakt@twojafirma.pl',
  city: 'Warszawa',
  hours: 'Pon-Pt: 8:00 - 21:00',
  facebookUrl: 'https://www.facebook.com/twojafirma',
};

// Dlaczego: renderujemy taki sam markup jak blok (pasek kontaktowy, pasek
// main, sticky header, drawer) so that the test sticks to the HTML structure.
function renderNavbarContactHtml(data: NavbarContactData = DEFAULT_DATA): string {
  const { menu, cta, phone, email, city, hours, facebookUrl } = data;
  const phoneHref = `tel:${phone.replace(/\s/g, '')}`;

  const navMain = `
    <div class="ui-container ui-nav-main relative flex items-center justify-between lg:justify-center">
      <a href="/" class="relative z-[1010] flex items-center transition-colors duration-300 lg:absolute lg:left-[var(--spacing-container-px)] lg:top-1/2 lg:-translate-y-1/2">
        <img class="h-9 w-auto object-contain lg:h-11" alt="Logo" />
      </a>
      <nav class="hidden items-center gap-6 lg:flex lg:flex-1 lg:justify-center lg:gap-8 xl:gap-10 lg:-translate-x-8" aria-label="Nawigacja główna">
        ${menu
          .map(
            (item) =>
              `<a href="${item.href}" class="ui-nav-bar-link flex items-center text-inherit opacity-75 hover:text-brand-accent hover:opacity-100">${item.label}</a>`,
          )
          .join('')}
      </nav>
      <div class="relative z-[1010] flex items-center gap-3 lg:gap-4 lg:absolute lg:right-[var(--spacing-container-px)] lg:top-1/2 lg:-translate-y-1/2">
        <a href="${phoneHref}" class="ui-nav-phone hidden xl:flex">
          <span class="ui-nav-phone-label">Zadzwoń teraz</span>
          <span>${phone}</span>
        </a>
        <a href="${cta.href}" class="ui-button ui-button-primary ui-nav-cta hidden sm:flex">
          <span class="ui-button-text-default">${cta.label}</span>
          <span class="ui-button-text-hover">${cta.hoverText}</span>
        </a>
        <button type="button" data-navbar-toggle class="ui-nav-menu-toggle lg:hidden" aria-expanded="false">
          <span class="ui-nav-menu-toggle__bar"></span>
          <span class="ui-nav-menu-toggle__bar"></span>
          <span class="ui-nav-menu-toggle__bar"></span>
        </button>
      </div>
    </div>`;

  const contactBar = `
    <div class="ui-nav-contact-bar hidden lg:flex">
      <span class="ui-nav-contact-link"><i class="ph ph-map-pin"></i>${city}</span>
      <span class="ui-nav-contact-divider" aria-hidden="true"></span>
      <a href="mailto:${email}" class="ui-nav-contact-link"><i class="ph ph-envelope-simple"></i>${email}</a>
      <div class="ui-nav-contact-right">
        <span class="ui-nav-contact-link"><i class="ph ph-clock"></i>${hours}</span>
        <span class="ui-nav-contact-divider" aria-hidden="true"></span>
        ${
          facebookUrl
            ? `<a href="${facebookUrl}" class="ui-nav-social-link" aria-label="Facebook" target="_blank" rel="noopener"><i class="ph ph-facebook-logo"></i></a>`
            : ''
        }
      </div>
    </div>`;

  return `
    <header data-site-header class="ui-navcontact relative z-[1000] w-full overflow-hidden bg-white transition-all duration-300 nav-transparent">
      ${contactBar}
      ${navMain}
    </header>
    <header data-sticky-header class="ui-navcontact fixed top-0 left-0 z-[999] w-full bg-white transition-all duration-[400ms]" style="transform: translateY(-100%)">
      ${navMain}
    </header>
    <div id="site-nav-drawer" class="ui-nav-drawer-root" role="presentation">
      <div class="ui-nav-drawer-backdrop" data-navbar-close aria-hidden="true"></div>
      <aside class="ui-nav-drawer--sheet" role="dialog" aria-modal="true" aria-label="Menu nawigacji">
        <nav class="ui-nav-drawer__nav" aria-label="Nawigacja główna">
          ${menu
            .map((item) => `<a href="${item.href}" class="ui-nav-drawer__link" data-navbar-close>${item.label}</a>`)
            .join('')}
        </nav>
      </aside>
    </div>`;
}

describe('NavbarContactBlock, kontrakt renderowania', () => {
  it('renderuje header[data-site-header] z klasami bloku', () => {
    const $ = cheerio.load(renderNavbarContactHtml());
    const header = $('header[data-site-header]');
    expect(header.length).toBe(1);
    expect(header.hasClass('ui-navcontact')).toBe(true);
    expect(header.hasClass('nav-transparent')).toBe(true);
  });

  describe('pasek kontaktowy', () => {
    it('renderuje .ui-nav-contact-bar z miastem, emailem i godzinami', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const bar = $('.ui-nav-contact-bar');
      expect(bar.length).toBe(1);
      expect(bar.hasClass('hidden')).toBe(true);
      expect(bar.hasClass('lg:flex')).toBe(true);
      const links = bar.find('.ui-nav-contact-link');
      expect(links.length).toBe(3);
      expect(links.first().text()).toContain('Warszawa');
      expect(links.eq(1).text()).toContain('kontakt@twojafirma.pl');
      expect(links.eq(2).text()).toContain('Pon-Pt: 8:00 - 21:00');
    });

    it('mailto prowadzi na email z danych', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      expect($('.ui-nav-contact-link[href^="mailto:"]').attr('href')).toBe(
        'mailto:kontakt@twojafirma.pl',
      );
    });

    it('renderuje social link tylko gdy jest facebookUrl', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      expect($('.ui-nav-social-link').length).toBe(1);
      expect($('.ui-nav-social-link').attr('aria-label')).toBe('Facebook');
      expect($('.ui-nav-social-link').attr('target')).toBe('_blank');
      const withoutSocial = cheerio.load(renderNavbarContactHtml({ ...DEFAULT_DATA, facebookUrl: '' }));
      expect(withoutSocial('.ui-nav-social-link').length).toBe(0);
    });

    it('pasek ma separatory ui-nav-contact-divider', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      expect($('.ui-nav-contact-divider').length).toBe(2);
    });
  });

  describe('pasek główny', () => {
    it('renderuje nav z menu (4 linki ui-nav-bar-link)', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const nav = $('header[data-site-header] nav[aria-label="Nawigacja główna"]');
      expect(nav.length).toBe(1);
      const links = nav.find('.ui-nav-bar-link');
      expect(links.length).toBe(4);
      expect(links.first().text()).toBe('O nas');
      expect(links.first().attr('href')).toBe('/o-nas/');
    });

    it('linki menu mają trailing slash', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const hrefs = $('.ui-nav-bar-link')
        .toArray()
        .map((el) => $(el).attr('href'))
        .filter((href): href is string => typeof href === 'string');
      expect(hrefs.every((h) => h.endsWith('/'))).toBe(true);
    });

    it('renderuje telefon ui-nav-phone z etykietą "Zadzwoń teraz"', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      // Why: the phone appears twice (main header + sticky), that's why
      // skopujemy do pierwszego headera [data-site-header].
      const phone = $('[data-site-header] a.ui-nav-phone');
      expect(phone.length).toBe(1);
      expect(phone.attr('href')).toBe('tel:+48123456789');
      expect(phone.find('.ui-nav-phone-label').text()).toBe('Zadzwoń teraz');
      expect(phone.text()).toContain('+48 123 456 789');
    });

    it('renderuje CTA ui-nav-cta z label i hoverText', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      // Why: CTA appears twice (main header + sticky), that's why
      // skopujemy do pierwszego headera [data-site-header].
      const cta = $('[data-site-header] a.ui-nav-cta');
      expect(cta.length).toBe(1);
      expect(cta.attr('href')).toBe('/kontakt/');
      expect(cta.find('.ui-button-text-default').text()).toBe('Kontakt');
      expect(cta.find('.ui-button-text-hover').text()).toBe('Pisz!');
    });

    it('renderuje MenuToggle z data-navbar-toggle', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      expect($('header[data-site-header] button[data-navbar-toggle]').length).toBe(1);
    });
  });

  describe('sticky header', () => {
    it('renderuje header[data-sticky-header] ukryty translateY(-100%)', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const sticky = $('header[data-sticky-header]');
      expect(sticky.length).toBe(1);
      expect(sticky.hasClass('fixed')).toBe(true);
      expect(sticky.attr('style')).toContain('translateY(-100%)');
    });

    it('sticky header zawiera ten sam pasek główny (menu i telefon)', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const sticky = $('header[data-sticky-header]');
      expect(sticky.find('.ui-nav-bar-link').length).toBe(4);
      expect(sticky.find('a.ui-nav-phone').length).toBe(1);
    });
  });

  describe('drawer', () => {
    it('renderuje #site-nav-drawer z role="presentation"', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      const drawer = $('#site-nav-drawer');
      expect(drawer.length).toBe(1);
      expect(drawer.attr('role')).toBe('presentation');
      expect(drawer.find('.ui-nav-drawer-backdrop[data-navbar-close]').length).toBe(1);
    });

    it('drawer ma menu z tymi samymi pozycjami co pasek główny', () => {
      const $ = cheerio.load(renderNavbarContactHtml());
      expect($('#site-nav-drawer .ui-nav-drawer__link').length).toBe(4);
    });
  });

  it('nie zawiera href="#" (martwe linki)', () => {
    const html = renderNavbarContactHtml();
    expect(html).not.toContain('href="#"');
  });

  it('nie zawiera danych klienta marek-jodlowski', () => {
    const html = renderNavbarContactHtml();
    expect(html).not.toContain('luksusowaprzestrzen');
    expect(html).not.toContain('786 202 542');
  });
});
