import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// ServicesStudioGridBlock to detect regressions in bare metal rendering
// full build. Pattern: hero-contract.test.ts.

interface ServiceItem {
  icon?: string;
  title: string;
  desc: string;
}

interface ServicesStudioData {
  sectionId?: string;
  heading?: string;
  items?: ServiceItem[];
}

const DEFAULT_ITEMS: ServiceItem[] = [
  { icon: 'microphone', title: 'Doradztwo', desc: 'Konsultacje na starcie projektu.' },
  { icon: 'sliders', title: 'Projektowanie', desc: 'Koncepcje szyte na miarę.' },
  { icon: 'wifi-high', title: 'Wdrożenie', desc: 'Sprawna realizacja.' },
  { icon: 'speaker-high', title: 'Wsparcie', desc: 'Stała opieka po wdrożeniu.' },
  { icon: 'waveform', title: 'Szkolenia', desc: 'Praktyczne szkolenia zespołu.' },
];

// Why: Fixed pillar heights reproduce the rhythm of the "sound wave"
// z komponentu (wave bars na dole karty).
const WAVE_BARS = [30, 50, 70, 45, 60];

function renderServicesStudioHtml(data: ServicesStudioData): string {
  const {
    sectionId = 'uslugi',
    heading = 'Usługi',
    items = DEFAULT_ITEMS,
  } = data;

  const cardsHtml = items
    .map((item) => `
      <div class="group relative bg-white px-6 py-10 flex flex-col border border-neutral-200 transition-all duration-500 hover:-translate-y-1 hover:shadow-lg">
        <div class="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-neutral-100 via-neutral-400 to-neutral-100 opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <div class="relative mb-6 flex items-center gap-3">
          <div class="size-10 shrink-0 rounded-sm border border-neutral-200 flex items-center justify-center transition-all duration-500 group-hover:border-neutral-500 group-hover:shadow-sm">
            <i class="ph ph-${item.icon || 'star'} size-5 text-neutral-400 group-hover:text-neutral-700 transition-colors"></i>
          </div>
          <div class="flex-1 h-px bg-neutral-200"></div>
          <div class="size-1 rounded-full bg-neutral-300"></div>
        </div>
        <div class="flex-1">
          <h3 class="text-xs font-bold tracking-[0.15em] text-neutral-900 uppercase">${item.title}</h3>
          <div class="mt-3 h-px w-6 bg-neutral-300"></div>
          <p class="leading-relaxed mt-3 text-xs text-neutral-500">${item.desc}</p>
        </div>
        <div class="mt-6 flex items-end gap-[2px] h-6">
          ${WAVE_BARS.map((height) => `<div class="flex-1 bg-neutral-200 rounded-t transition-all duration-300 group-hover:bg-neutral-400" style="height: ${height}%"></div>`).join('')}
        </div>
      </div>`)
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-base relative overflow-hidden">
    <div class="ui-container">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="font-heading font-bold text-3xl font-light tracking-[0.08em] text-neutral-900 sm:text-4xl">${heading}</h2>
      </div>
      <div class="mt-16 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-px bg-neutral-200">
        ${cardsHtml}
      </div>
    </div>
  </section>`;
}

describe('ServicesStudioGrid, kontrakt renderowania', () => {
  const defaultData: ServicesStudioData = {
    heading: 'Usługi',
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderServicesStudioHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('uslugi');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderServicesStudioHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje h2 z headingiem', () => {
    const $ = cheerio.load(renderServicesStudioHtml(defaultData));
    expect($('h2').length).toBe(1);
    expect($('h2').text()).toContain('Usługi');
  });

  describe('grid', () => {
    it('grid jest mobile-first (grid-cols-1 sm:grid-cols-2 lg:grid-cols-5)', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const grid = $('.grid');
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('sm:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-5')).toBe(true);
    });

    it('grid używa gap-px i bg-neutral-200 (linie między kartami)', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const grid = $('.grid');
      expect(grid.hasClass('gap-px')).toBe(true);
      expect(grid.hasClass('bg-neutral-200')).toBe(true);
    });

    it('renderuje dokładnie 5 kart', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      expect($('div.group.relative').length).toBe(5);
    });

    it('każda karta ma hover: -translate-y-1 i shadow-lg', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      $('div.group.relative').each((_, el) => {
        expect($(el).hasClass('hover:-translate-y-1')).toBe(true);
        expect($(el).hasClass('hover:shadow-lg')).toBe(true);
      });
    });
  });

  describe('ikony', () => {
    it('renderuje ikonę w każdej karcie z klasą ph-', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      expect($('i.ph').length).toBe(5);
      $('i.ph').each((_, el) => {
        expect($(el).attr('class')).toContain('ph-');
      });
    });

    it('ikony mają nazwy z danych (microphone, sliders, wifi-high, speaker-high, waveform)', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      expect($('i.ph-microphone').length).toBe(1);
      expect($('i.ph-sliders').length).toBe(1);
      expect($('i.ph-wifi-high').length).toBe(1);
      expect($('i.ph-speaker-high').length).toBe(1);
      expect($('i.ph-waveform').length).toBe(1);
    });
  });

  describe('karta usługi', () => {
    it('h3 jest uppercase z trackingiem', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const firstH3 = $('h3').first();
      expect(firstH3.hasClass('uppercase')).toBe(true);
      expect(firstH3.hasClass('tracking-[0.15em]')).toBe(true);
      expect(firstH3.text()).toBe('Doradztwo');
    });

    it('opis renderuje się w karcie', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      expect($('p').first().text()).toContain('Konsultacje na starcie projektu.');
    });

    it('karta ma gradientowy pasek na hover', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const bar = $('div.group.relative').first().find('.bg-gradient-to-r');
      expect(bar.length).toBe(1);
      expect(bar.hasClass('opacity-0')).toBe(true);
      expect(bar.hasClass('group-hover:opacity-100')).toBe(true);
    });
  });

  describe('wave bars', () => {
    it('każda karta ma 5 słupków z wysokością inline', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      $('div.group.relative').each((_, el) => {
        const bars = $(el).find('[style*="height"]');
        expect(bars.length).toBe(5);
      });
    });

    it('słupki mają style height z wartościami procentowymi', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const bars = $('div.group.relative').first().find('[style*="height"]');
      const heights = bars.toArray().map((el) => $(el).attr('style'));
      expect(heights).toEqual([
        'height: 30%',
        'height: 50%',
        'height: 70%',
        'height: 45%',
        'height: 60%',
      ]);
    });

    it('słupki zmieniają kolor na hover karty', () => {
      const $ = cheerio.load(renderServicesStudioHtml(defaultData));
      const bar = $('div.group.relative').first().find('[style*="height"]').first();
      expect(bar.hasClass('group-hover:bg-neutral-400')).toBe(true);
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderServicesStudioHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
