import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// TransformationsWallBlock (visual copy of the "wall of transformations" from tom-ros),
// to detect regressions in rendering without running a full build.
// Wzorzec: hero-cinematic-contract.test.ts i marquee-wall-contract.test.ts.

interface TransformImage {
  src?: string;
  thumb?: string;
  alt?: string;
}

interface TransformWallData {
  sectionId?: string;
  title?: string;
  description?: string;
  images?: TransformImage[];
  wallLabel?: string;
  wallEmptyState?: string;
  headingTag?: string;
}

const DEFAULT_IMAGES: TransformImage[] = Array.from({ length: 18 }, (_, i) => ({
  src: `/assets/placeholders/image-${i % 3 === 0 ? 'portrait' : i % 3 === 1 ? 'square' : 'landscape'}.svg`,
  alt: `Metamorfoza ${i + 1}`,
}));

// Dlaczego: renderujemy statyczny HTML 1:1 z komponentu, bez importowania Astro
// in vitest, because .astro components require the Astro compiler.
function renderTransformationsWallHtml(data: TransformWallData): string {
  const {
    sectionId = 'metamorfozy',
    title = 'Metamorfozy',
    description = '',
    images: rawImages = [],
    wallLabel = 'Realne efekty',
    wallEmptyState = 'Brak metamorfoz do wyświetlenia.',
    headingTag = 'h2',
  } = data;

  const images = Array.isArray(rawImages) ? rawImages.filter((image) => image?.src) : [];

  const preloadHtml = images
    .slice(0, 6)
    .map((image) => `<link rel="preload" as="image" href="${image.thumb || image.src}" />`)
    .join('');

  const headerHtml = `
    <div class="space-y-4">
      <span class="ui-type-accent-label block">${wallLabel}</span>
      <${headingTag} class="font-heading font-bold ui-type-section-title">${title}</${headingTag}>
      <p class="leading-relaxed ui-type-body">${description}</p>
    </div>`;

  // Dlaczego: karta metamorfozy - border-brand-dark/15 zamiast border-outline-variant
  // (kontrakt wizualny), numer w font-accent (Barlow Condensed) inline.
  const cardHtml = (image: TransformImage, number: number) => `
    <div class="group relative w-[150px] md:w-[260px] aspect-[3/4] shrink-0 cursor-zoom-in overflow-hidden border border-brand-dark/15 bg-surface-dim transition-colors duration-300 hover:border-brand-primary" data-lightbox data-href="${image.src}" data-title="${image.alt || ''}">
      <img src="${image.src}" alt="${image.alt || ''}" class="absolute inset-0 h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-105" />
      <div class="pointer-events-none absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-black/70 to-transparent"></div>
      <span class="absolute bottom-3 left-3 text-sm font-bold uppercase tracking-[0.2em] text-white" style="font-family: var(--font-accent, 'Barlow Condensed'), sans-serif;">#${number}</span>
    </div>`;

  // Why: marquee row - .ui-wall class (hover pause + reduced-motion from core.css),
  // inline sidemask and doubled list ([...group, ...group]) for seamless looping.
  const rowHtml = (direction: 'normal' | 'reverse', duration: string, group: TransformImage[]) => `
    <div class="ui-wall relative z-10 overflow-hidden py-1">
      <div style="mask-image: linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%); -webkit-mask-image: linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%);">
        <div class="flex gap-3 md:gap-4" style="width: max-content; animation: ui-wall-scroll ${duration} linear infinite; animation-direction: ${direction};">
          ${[...group, ...group].map((image) => cardHtml(image, 1)).join('')}
        </div>
      </div>
    </div>`;

  const splitAt = Math.ceil(images.length / 3);
  const groups: TransformImage[][] = [];
  for (let i = 0; i < 3; i++) {
    groups.push(images.slice(i * splitAt, (i + 1) * splitAt));
  }

  const mobileRows = [
    rowHtml('normal', '30s', groups[0] || []),
    rowHtml('reverse', '40s', groups[1] || []),
    rowHtml('normal', '50s', groups[2] || []),
  ].join('');

  const desktopRows = [
    rowHtml('normal', '40s', groups[0] || []),
    rowHtml('reverse', '55s', groups[1] || []),
    rowHtml('normal', '70s', groups[2] || []),
  ].join('');

  const wallHtml = images.length > 0
    ? `<div class="relative isolate mt-10 space-y-4 md:space-y-5">
        <div class="md:hidden">${mobileRows}</div>
        <div class="hidden md:block">${desktopRows}</div>
      </div>`
    : `<div class="ui-container">
        <div class="mt-10 rounded-md border border-outline-variant bg-surface-dim py-20 text-center">
          <p class="leading-relaxed ui-type-body">${wallEmptyState}</p>
        </div>
      </div>`;

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    ${preloadHtml}
    <div class="ui-container">
      ${headerHtml}
    </div>
    ${wallHtml}
  </section>`;
}

describe('TransformationsWallBlock, kontrakt renderowania', () => {
  const defaultData: TransformWallData = {
    title: 'Metamorfozy',
    description: 'Realne efekty pracy z podopiecznymi.',
    images: DEFAULT_IMAGES,
    wallLabel: 'Realne efekty',
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('metamorfozy');
  });

  it('renderuje .ui-container', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje wallLabel jako .ui-type-accent-label', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('.ui-type-accent-label').first().text()).toBe('Realne efekty');
  });

  it('renderuje tytuł w h2 i opis', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('h2').text()).toContain('Metamorfozy');
    expect($('p').first().text()).toContain('Realne efekty pracy');
  });

  it('renderuje 6 rzędów .ui-wall (3 mobile + 3 desktop)', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('.ui-wall').length).toBe(6);
    expect($('div.md\\:hidden .ui-wall').length).toBe(3);
    expect($('div.hidden.md\\:block .ui-wall').length).toBe(3);
  });

  it('mobile rzędy mają animacje 30s/40s/50s i środkowy jest reverse', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const mobileTracks = $('div.md\\:hidden .ui-wall > div > div');
    expect(mobileTracks.eq(0).attr('style')).toContain('ui-wall-scroll 30s');
    expect(mobileTracks.eq(1).attr('style')).toContain('ui-wall-scroll 40s');
    expect(mobileTracks.eq(2).attr('style')).toContain('ui-wall-scroll 50s');
    expect(mobileTracks.eq(0).attr('style')).toContain('animation-direction: normal');
    expect(mobileTracks.eq(1).attr('style')).toContain('animation-direction: reverse');
    expect(mobileTracks.eq(2).attr('style')).toContain('animation-direction: normal');
  });

  it('desktop rzędy mają animacje 40s/55s/70s i środkowy jest reverse', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const desktopTracks = $('div.hidden.md\\:block .ui-wall > div > div');
    expect(desktopTracks.eq(0).attr('style')).toContain('ui-wall-scroll 40s');
    expect(desktopTracks.eq(1).attr('style')).toContain('ui-wall-scroll 55s');
    expect(desktopTracks.eq(2).attr('style')).toContain('ui-wall-scroll 70s');
    expect(desktopTracks.eq(1).attr('style')).toContain('animation-direction: reverse');
  });

  it('track ma width: max-content (pętla translateX(-50%))', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const track = $('.ui-wall > div > div').first();
    expect(track.attr('style')).toContain('width: max-content');
  });

  it('maska boczna rozmywa wejście i wyjście rzędu', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const mask = $('.ui-wall > div').first();
    expect(mask.attr('style')).toContain('mask-image: linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%)');
  });

  it('lista w rzędzie jest podwojona (18 zdjęć = 36 kart w każdym rzędzie)', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const firstRowCards = $('.ui-wall').first().find('[data-lightbox]');
    expect(firstRowCards.length).toBe(12);
  });

  it('karty mają data-lightbox, data-href i data-title', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const card = $('[data-lightbox]').first();
    expect(card.attr('data-href')).toBe('/assets/placeholders/image-portrait.svg');
    expect(card.attr('data-title')).toBe('Metamorfoza 1');
  });

  it('karty mają border-brand-dark/15 i cursor-zoom-in', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const card = $('[data-lightbox]').first();
    expect(card.hasClass('border-brand-dark/15')).toBe(true);
    expect(card.hasClass('cursor-zoom-in')).toBe(true);
    expect(card.hasClass('aspect-[3/4]')).toBe(true);
  });

  it('numer metamorfozy jest w font-accent (Barlow Condensed) i zaczyna się od #', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    const number = $('.ui-wall span').first();
    expect(number.text()).toMatch(/^#\d+$/);
    expect(number.attr('style')).toContain("font-family: var(--font-accent, 'Barlow Condensed')");
  });

  it('renderuje preload linki dla pierwszych zdjęć', () => {
    const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
    expect($('link[rel="preload"][as="image"]').length).toBe(6);
  });

  describe('hierarchia nagłówków', () => {
    it('domyślnie używa h2, zero h1', () => {
      const $ = cheerio.load(renderTransformationsWallHtml(defaultData));
      expect($('h2').length).toBe(1);
      expect($('h1').length).toBe(0);
    });

    it('używa h1 gdy headingTag = h1 (podstrony)', () => {
      const $ = cheerio.load(renderTransformationsWallHtml({ ...defaultData, headingTag: 'h1' }));
      expect($('h1').length).toBe(1);
      expect($('h2').length).toBe(0);
    });
  });

  describe('stan pusty', () => {
    it('renderuje wallEmptyState gdy brak images', () => {
      const $ = cheerio.load(renderTransformationsWallHtml({ ...defaultData, images: [] }));
      expect($('p').text()).toContain('Brak metamorfoz do wyświetlenia.');
      expect($('.ui-wall').length).toBe(0);
    });

    it('nie renderuje rzędów gdy brak images', () => {
      const $ = cheerio.load(renderTransformationsWallHtml({ ...defaultData, images: [] }));
      expect($('[data-lightbox]').length).toBe(0);
    });
  });
});
