// Why: section-registry remains the public entry point for PageBuilder, Studio
// and the component gallery.
// Block entries are divided by domain, while the following export retains
// the existing SECTION_REGISTRY contract and the order of the block directory.
import type { SectionEntry } from './section-registry/types';
import { shellSections } from './section-registry/shell';
import { heroSections } from './section-registry/hero';
import { aboutSections } from './section-registry/about';
import { servicesSections } from './section-registry/services';
import { portfolioSections } from './section-registry/portfolio';
import { processSections } from './section-registry/process';
import { socialSections } from './section-registry/social';
import { faqSections } from './section-registry/faq';
import { contactSections } from './section-registry/contact';
import { ctaSections } from './section-registry/cta';
import { contentSections } from './section-registry/content';

export { SECTION_GROUPS } from './section-registry/types';
export type { SectionEntry, SectionGroup, VariantEntry, StudioSource } from './section-registry/types';

export const SECTION_REGISTRY: Record<string, SectionEntry> = {
  hero: heroSections.hero,
  heroVideo: heroSections.heroVideo,
  features: servicesSections.features,
  novaServices: servicesSections.novaServices,
  about: aboutSections.about,
  novaTeam: aboutSections.novaTeam,
  marquee: aboutSections.marquee,
  theme: shellSections.theme,
  navbar: shellSections.navbar,
  footer: shellSections.footer,
  portfolio: portfolioSections.portfolio,
  faq: faqSections.faq,
  testimonials: socialSections.testimonials,
  contact: contactSections.contact,
  appManagement: aboutSections.appManagement,
  cta: ctaSections.cta,
  novaCta: ctaSections.novaCta,
  blog: contentSections.blog,
  gallery: portfolioSections.gallery,
  galleryCrossfade: portfolioSections.galleryCrossfade,
  marqueeWall: portfolioSections.marqueeWall,
  trustBar: aboutSections.trustBar,
  processTimeline: processSections.processTimeline,
  heroCinematic: heroSections.heroCinematic,
  ctaSpectrum: ctaSections.ctaSpectrum,
  aboutMarquee: aboutSections.aboutMarquee,
  servicesStudio: servicesSections.servicesStudio,
  galleryStudio: portfolioSections.galleryStudio,
  playerEmbed: portfolioSections.playerEmbed,
  contactStudio: contactSections.contactStudio,
  heroTomRos: heroSections.heroTomRos,
  ctaTomRos: ctaSections.ctaTomRos,
  transformationsWall: portfolioSections.transformationsWall,
  competitions: portfolioSections.competitions,
  contactEditorial: contactSections.contactEditorial,
  featuresOffer: servicesSections.featuresOffer,
  aboutTomRos: aboutSections.aboutTomRos,
  heroLaw: heroSections.heroLaw,
  crossBorder: contentSections.crossBorder,
  specializationsGrid: servicesSections.specializationsGrid,
  aboutLaw: aboutSections.aboutLaw,
  onlineAdvice: contactSections.onlineAdvice,
  ctaContactForm: ctaSections.ctaContactForm,
  publicInfo: contentSections.publicInfo,
  heroSplit: heroSections.heroSplit,
  aboutSplit: aboutSections.aboutSplit,
  servicesZigzag: servicesSections.servicesZigzag,
  servicesGrid: servicesSections.servicesGrid,
  servicesCards: servicesSections.servicesCards,
  featuresGrid: servicesSections.featuresGrid,
  faqAccordion: faqSections.faqAccordion,
  footerContact: shellSections.footerContact,
  navbarContact: shellSections.navbarContact,
  heroEditorial: heroSections.heroEditorial,
  uspPremium: aboutSections.uspPremium,
  filterableCards: servicesSections.filterableCards,
  featureGrid: servicesSections.featureGrid,
  contactPremium: contactSections.contactPremium,
  processTimelineScroll: processSections.processTimelineScroll,
  heroPhoto: heroSections.heroPhoto,
  lcNavbar: shellSections.lcNavbar,
  lcSubnav: shellSections.lcSubnav,
  servicesMediaCards: servicesSections.servicesMediaCards,
  processIconSteps: processSections.processIconSteps,
  timelineAlternate: processSections.timelineAlternate,
  aboutExpert: aboutSections.aboutExpert,
  audienceSplit: aboutSections.audienceSplit,
  knowledgeCards: contentSections.knowledgeCards,
  faqLean: faqSections.faqLean,
  contactInfoForm: contactSections.contactInfoForm,
  ctaLean: ctaSections.ctaLean,
  heroStats: heroSections.heroStats,
  aboutSplitLean: aboutSections.aboutSplitLean,
  stepsNumbered: processSections.stepsNumbered,
  processRecruitment: processSections.processRecruitment,
  logoGrid: aboutSections.logoGrid,
  heroAccommodation: heroSections.heroAccommodation,
  accommodationCards: servicesSections.accommodationCards,
  roomDetail: contentSections.roomDetail,
  priceTable: servicesSections.priceTable,
  pageIntro: contentSections.pageIntro,
  ctaBridge: ctaSections.ctaBridge,
  calculator: ctaSections.calculator,
  heroWireframe: heroSections.heroWireframe,
  heroCountdown: heroSections.heroCountdown,
  universityFields: servicesSections.universityFields,
  aboutWireframe: aboutSections.aboutWireframe,
  saunaBenefits: aboutSections.saunaBenefits,
  saunaPricing: servicesSections.saunaPricing,
  materials: servicesSections.materials,
  purInsulation: servicesSections.purInsulation,
  saunaGallery: portfolioSections.saunaGallery,
  saunaHowItWorks: processSections.saunaHowItWorks,
  production: processSections.production,
  contactWireframe: contactSections.contactWireframe,
  calculatorWireframe: ctaSections.calculatorWireframe,
  faqFlat: faqSections.faqFlat,
  faqUp: faqSections.faqUp,
  faq3: faqSections.faq3,
  ctaUp: ctaSections.ctaUp,
};
