import type { StudioAdapter } from "./types";

const BLUSH_ICON =
  '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16" stroke-width="2" stroke-linecap="round"/></svg>';

export const blushStudioAdapter: StudioAdapter = {
  id: "blush",
  label: "Blush",
  groups: [
    { id: "theme", label: "Motyw" },
    { id: "navbar", label: "Menu" },
    { id: "footer", label: "Footer" },
    { id: "sections", label: "Sekcje BLUSH" },
    { id: "conversion", label: "Konwersja i dodatkowe sekcje" },
  ],
  sections: [
    {
      id: "navbar",
      label: "Navbar",
      groupId: "navbar",
      icon: BLUSH_ICON,
      options: ["centered", "floating", "local"],
      defaultVariant: "centered",
      hint: "Układ menu dla strony afiliacyjnej",
    },
    {
      id: "theme",
      label: "Theme",
      groupId: "theme",
      icon: BLUSH_ICON,
      options: ["blush", "default", "fix-bud", "gold"],
      defaultVariant: "blush",
      hint: "Podgląd motywów wizualnych",
    },
    {
      id: "section-pattern",
      label: "Tło sekcji",
      groupId: "theme",
      icon: BLUSH_ICON,
      options: ["off", "repeat", "mesh", "noise"],
      defaultVariant: "off",
      hint: "Dodatkowy wzorzec tła sekcji",
    },
    {
      id: "hero",
      label: "Hero",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["blush-lead", "registry-centered", "registry-split"],
      defaultVariant: "blush-lead",
      hint: "Główny wariant sekcji hero",
    },
    {
      id: "features",
      label: "Oferty",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "list", "zigzag"],
      defaultVariant: "grid",
      hint: "Układ prezentacji ofert bankowych",
    },
    {
      id: "services",
      label: "Services",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "list", "split"],
      defaultVariant: "off",
      hint: "Dodatkowe sekcje usługowe",
    },
    {
      id: "steps",
      label: "Kroki",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "vertical", "horizontal", "zigzag"],
      defaultVariant: "off",
      hint: "Wariant kroków realizacji",
    },
    {
      id: "contact-form",
      label: "Contact Form",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "simple", "split", "floating"],
      defaultVariant: "off",
      hint: "Wariant formularza kontaktowego",
    },
    {
      id: "contact",
      label: "Contact",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "minimal", "split", "full"],
      defaultVariant: "off",
      hint: "Sekcja kontaktu",
    },
    {
      id: "stats",
      label: "Stats",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "counters", "metrics-bar", "bento"],
      defaultVariant: "off",
      hint: "Wariant statystyk",
    },
    {
      id: "brands",
      label: "Brands",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "cloud", "investors", "split"],
      defaultVariant: "off",
      hint: "Partnerzy i logotypy",
    },
    {
      id: "about",
      label: "About",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "split", "centered", "story", "metrics"],
      defaultVariant: "off",
      hint: "Wariant sekcji o projekcie",
    },
    {
      id: "portfolio",
      label: "Portfolio",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "masonry", "bento", "carousel", "categorized", "marquee", "double-marquee"],
      defaultVariant: "off",
      hint: "Sekcje prezentacyjne",
    },
    {
      id: "case-studies",
      label: "Case studies",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "featured", "timeline"],
      defaultVariant: "off",
      hint: "Wariant case studies",
    },
    {
      id: "blog",
      label: "Blog",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "list", "featured"],
      defaultVariant: "off",
      hint: "Wariant listy wpisów",
    },
    {
      id: "testimonials",
      label: "Testimonials",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "columns", "carousel", "marquee", "double-marquee"],
      defaultVariant: "off",
      hint: "Wariant opinii",
    },
    {
      id: "team",
      label: "Team",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "simple", "highlight", "dense"],
      defaultVariant: "off",
      hint: "Wariant zespołu",
    },
    {
      id: "faq",
      label: "FAQ",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "simple", "grid", "list", "flat", "grouped"],
      defaultVariant: "off",
      hint: "Wariant pytań i odpowiedzi",
    },
    {
      id: "scope",
      label: "Zakres",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "split", "cards", "accordion"],
      defaultVariant: "off",
      hint: "Zakres usług",
    },
    {
      id: "benefits",
      label: "Korzyści",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "grid", "zigzag", "band"],
      defaultVariant: "off",
      hint: "Sekcja korzyści",
    },
    {
      id: "location",
      label: "Lokalizacja",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "list-map", "city-cards", "map-panel", "split", "map-hero", "cards"],
      defaultVariant: "off",
      hint: "Wariant lokalizacji i map",
    },
    {
      id: "before-after",
      label: "Before & After",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "slider", "cards"],
      defaultVariant: "off",
      hint: "Wariant porównań",
    },
    {
      id: "pricing",
      label: "Dlaczego warto",
      groupId: "sections",
      icon: BLUSH_ICON,
      options: ["off", "simple", "minimal"],
      defaultVariant: "simple",
      hint: "Sekcja wartości i korzyści",
    },
    {
      id: "cta",
      label: "CTA",
      groupId: "conversion",
      icon: BLUSH_ICON,
      options: ["off", "centered", "banner"],
      defaultVariant: "centered",
      hint: "Końcowe wezwanie do sprawdzenia promocji",
    },
    {
      id: "newsletter",
      label: "Newsletter",
      groupId: "conversion",
      icon: BLUSH_ICON,
      options: ["off", "band", "split", "modal"],
      defaultVariant: "off",
      hint: "Wariant zapisu mailowego",
    },
    {
      id: "timeline",
      label: "Timeline",
      groupId: "conversion",
      icon: BLUSH_ICON,
      options: ["off", "zigzag", "vertical", "horizontal"],
      defaultVariant: "off",
      hint: "Wariant osi czasu",
    },
    {
      id: "sidebar",
      label: "Sidebar strony",
      groupId: "conversion",
      icon: BLUSH_ICON,
      options: ["off", "toc", "toc-contact", "toc-promo"],
      defaultVariant: "off",
      hint: "Wariant bocznego panelu treści",
    },
    {
      id: "footer",
      label: "Footer",
      groupId: "footer",
      icon: BLUSH_ICON,
      options: ["columns", "minimal", "promo"],
      defaultVariant: "columns",
      hint: "Wariant stopki i linków prawnych",
    },
  ],
};
